//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBBWeb.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:5034/FBBProfileCustomer.svc")]
        public string WBBWeb_FBBProfileCustomer11_FBBProfileCustomer {
            get {
                return ((string)(this["WBBWeb_FBBProfileCustomer11_FBBProfileCustomer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.240.1.101:7201/EmployeeServiceWebServiceV2/EmployeeServiceWebServiceV2." +
            "jws")]
        public string WBBWeb_EmployeeServices_EmployeeServiceWebServiceV2Service {
            get {
                return ((string)(this["WBBWeb_EmployeeServices_EmployeeServiceWebServiceV2Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.240.1.101:7201/PartnerServiceWebServiceV2/PartnerServiceWebServiceV2.jw" +
            "s")]
        public string WBBWeb_PartnerServices_PartnerServiceWebServiceV2Service {
            get {
                return ((string)(this["WBBWeb_PartnerServices_PartnerServiceWebServiceV2Service"]));
            }
        }
    }
}
