//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WBBBusinessLayer.BindingQSServices {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="tuxsalt_Binding", Namespace="urn:tuxsalt.wsdl")]
    public partial class tuxsalt_BindingQSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback D_InsPMGwRecOperationCompleted;
        
        private System.Threading.SendOrPostCallback A_LstPMMobDtlOperationCompleted;
        
        private System.Threading.SendOrPostCallback A_ConfPMPayOperationCompleted;
        
        private System.Threading.SendOrPostCallback A_ConfPMOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback A_LstPMOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback A_LstPMETaxProfOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public tuxsalt_BindingQSService() {
            this.Url = global::WBBBusinessLayer.Properties.Settings.Default.WBBBusinessLayer_BindingQSServices_tuxsalt_BindingQSService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event D_InsPMGwRecCompletedEventHandler D_InsPMGwRecCompleted;
        
        /// <remarks/>
        public event A_LstPMMobDtlCompletedEventHandler A_LstPMMobDtlCompleted;
        
        /// <remarks/>
        public event A_ConfPMPayCompletedEventHandler A_ConfPMPayCompleted;
        
        /// <remarks/>
        public event A_ConfPMOrderCompletedEventHandler A_ConfPMOrderCompleted;
        
        /// <remarks/>
        public event A_LstPMOrderCompletedEventHandler A_LstPMOrderCompleted;
        
        /// <remarks/>
        public event A_LstPMETaxProfCompletedEventHandler A_LstPMETaxProfCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("D_InsPMGwRec", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("D_InsPMGwRecResponse", Namespace="urn:pack.tuxsalt_typedef.salt11")]
        public D_InsPMGwRecResponse D_InsPMGwRec([System.Xml.Serialization.XmlElementAttribute("D_InsPMGwRec", Namespace="urn:pack.tuxsalt_typedef.salt11")] D_InsPMGwRec D_InsPMGwRec1) {
            object[] results = this.Invoke("D_InsPMGwRec", new object[] {
                        D_InsPMGwRec1});
            return ((D_InsPMGwRecResponse)(results[0]));
        }
        
        /// <remarks/>
        public void D_InsPMGwRecAsync(D_InsPMGwRec D_InsPMGwRec1) {
            this.D_InsPMGwRecAsync(D_InsPMGwRec1, null);
        }
        
        /// <remarks/>
        public void D_InsPMGwRecAsync(D_InsPMGwRec D_InsPMGwRec1, object userState) {
            if ((this.D_InsPMGwRecOperationCompleted == null)) {
                this.D_InsPMGwRecOperationCompleted = new System.Threading.SendOrPostCallback(this.OnD_InsPMGwRecOperationCompleted);
            }
            this.InvokeAsync("D_InsPMGwRec", new object[] {
                        D_InsPMGwRec1}, this.D_InsPMGwRecOperationCompleted, userState);
        }
        
        private void OnD_InsPMGwRecOperationCompleted(object arg) {
            if ((this.D_InsPMGwRecCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.D_InsPMGwRecCompleted(this, new D_InsPMGwRecCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("A_LstPMMobDtl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("A_LstPMMobDtlResponse", Namespace="urn:pack.tuxsalt_typedef.salt11")]
        public A_LstPMMobDtlResponse A_LstPMMobDtl([System.Xml.Serialization.XmlElementAttribute("A_LstPMMobDtl", Namespace="urn:pack.tuxsalt_typedef.salt11")] A_LstPMMobDtl A_LstPMMobDtl1) {
            object[] results = this.Invoke("A_LstPMMobDtl", new object[] {
                        A_LstPMMobDtl1});
            return ((A_LstPMMobDtlResponse)(results[0]));
        }
        
        /// <remarks/>
        public void A_LstPMMobDtlAsync(A_LstPMMobDtl A_LstPMMobDtl1) {
            this.A_LstPMMobDtlAsync(A_LstPMMobDtl1, null);
        }
        
        /// <remarks/>
        public void A_LstPMMobDtlAsync(A_LstPMMobDtl A_LstPMMobDtl1, object userState) {
            if ((this.A_LstPMMobDtlOperationCompleted == null)) {
                this.A_LstPMMobDtlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnA_LstPMMobDtlOperationCompleted);
            }
            this.InvokeAsync("A_LstPMMobDtl", new object[] {
                        A_LstPMMobDtl1}, this.A_LstPMMobDtlOperationCompleted, userState);
        }
        
        private void OnA_LstPMMobDtlOperationCompleted(object arg) {
            if ((this.A_LstPMMobDtlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.A_LstPMMobDtlCompleted(this, new A_LstPMMobDtlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("A_ConfPMPay", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("A_ConfPMPayResponse", Namespace="urn:pack.tuxsalt_typedef.salt11")]
        public A_ConfPMPayResponse A_ConfPMPay([System.Xml.Serialization.XmlElementAttribute("A_ConfPMPay", Namespace="urn:pack.tuxsalt_typedef.salt11")] A_ConfPMPay A_ConfPMPay1) {
            object[] results = this.Invoke("A_ConfPMPay", new object[] {
                        A_ConfPMPay1});
            return ((A_ConfPMPayResponse)(results[0]));
        }
        
        /// <remarks/>
        public void A_ConfPMPayAsync(A_ConfPMPay A_ConfPMPay1) {
            this.A_ConfPMPayAsync(A_ConfPMPay1, null);
        }
        
        /// <remarks/>
        public void A_ConfPMPayAsync(A_ConfPMPay A_ConfPMPay1, object userState) {
            if ((this.A_ConfPMPayOperationCompleted == null)) {
                this.A_ConfPMPayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnA_ConfPMPayOperationCompleted);
            }
            this.InvokeAsync("A_ConfPMPay", new object[] {
                        A_ConfPMPay1}, this.A_ConfPMPayOperationCompleted, userState);
        }
        
        private void OnA_ConfPMPayOperationCompleted(object arg) {
            if ((this.A_ConfPMPayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.A_ConfPMPayCompleted(this, new A_ConfPMPayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("A_ConfPMOrder", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("A_ConfPMOrderResponse", Namespace="urn:pack.tuxsalt_typedef.salt11")]
        public A_ConfPMOrderResponse A_ConfPMOrder([System.Xml.Serialization.XmlElementAttribute("A_ConfPMOrder", Namespace="urn:pack.tuxsalt_typedef.salt11")] A_ConfPMOrder A_ConfPMOrder1) {
            object[] results = this.Invoke("A_ConfPMOrder", new object[] {
                        A_ConfPMOrder1});
            return ((A_ConfPMOrderResponse)(results[0]));
        }
        
        /// <remarks/>
        public void A_ConfPMOrderAsync(A_ConfPMOrder A_ConfPMOrder1) {
            this.A_ConfPMOrderAsync(A_ConfPMOrder1, null);
        }
        
        /// <remarks/>
        public void A_ConfPMOrderAsync(A_ConfPMOrder A_ConfPMOrder1, object userState) {
            if ((this.A_ConfPMOrderOperationCompleted == null)) {
                this.A_ConfPMOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnA_ConfPMOrderOperationCompleted);
            }
            this.InvokeAsync("A_ConfPMOrder", new object[] {
                        A_ConfPMOrder1}, this.A_ConfPMOrderOperationCompleted, userState);
        }
        
        private void OnA_ConfPMOrderOperationCompleted(object arg) {
            if ((this.A_ConfPMOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.A_ConfPMOrderCompleted(this, new A_ConfPMOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("A_LstPMOrder", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("A_LstPMOrderResponse", Namespace="urn:pack.tuxsalt_typedef.salt11")]
        public A_LstPMOrderResponse A_LstPMOrder([System.Xml.Serialization.XmlElementAttribute("A_LstPMOrder", Namespace="urn:pack.tuxsalt_typedef.salt11")] A_LstPMOrder A_LstPMOrder1) {
            object[] results = this.Invoke("A_LstPMOrder", new object[] {
                        A_LstPMOrder1});
            return ((A_LstPMOrderResponse)(results[0]));
        }
        
        /// <remarks/>
        public void A_LstPMOrderAsync(A_LstPMOrder A_LstPMOrder1) {
            this.A_LstPMOrderAsync(A_LstPMOrder1, null);
        }
        
        /// <remarks/>
        public void A_LstPMOrderAsync(A_LstPMOrder A_LstPMOrder1, object userState) {
            if ((this.A_LstPMOrderOperationCompleted == null)) {
                this.A_LstPMOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnA_LstPMOrderOperationCompleted);
            }
            this.InvokeAsync("A_LstPMOrder", new object[] {
                        A_LstPMOrder1}, this.A_LstPMOrderOperationCompleted, userState);
        }
        
        private void OnA_LstPMOrderOperationCompleted(object arg) {
            if ((this.A_LstPMOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.A_LstPMOrderCompleted(this, new A_LstPMOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("A_LstPMETaxProf", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("A_LstPMETaxProfResponse", Namespace="urn:pack.tuxsalt_typedef.salt11")]
        public A_LstPMETaxProfResponse A_LstPMETaxProf([System.Xml.Serialization.XmlElementAttribute("A_LstPMETaxProf", Namespace="urn:pack.tuxsalt_typedef.salt11")] A_LstPMETaxProf A_LstPMETaxProf1) {
            object[] results = this.Invoke("A_LstPMETaxProf", new object[] {
                        A_LstPMETaxProf1});
            return ((A_LstPMETaxProfResponse)(results[0]));
        }
        
        /// <remarks/>
        public void A_LstPMETaxProfAsync(A_LstPMETaxProf A_LstPMETaxProf1) {
            this.A_LstPMETaxProfAsync(A_LstPMETaxProf1, null);
        }
        
        /// <remarks/>
        public void A_LstPMETaxProfAsync(A_LstPMETaxProf A_LstPMETaxProf1, object userState) {
            if ((this.A_LstPMETaxProfOperationCompleted == null)) {
                this.A_LstPMETaxProfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnA_LstPMETaxProfOperationCompleted);
            }
            this.InvokeAsync("A_LstPMETaxProf", new object[] {
                        A_LstPMETaxProf1}, this.A_LstPMETaxProfOperationCompleted, userState);
        }
        
        private void OnA_LstPMETaxProfOperationCompleted(object arg) {
            if ((this.A_LstPMETaxProfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.A_LstPMETaxProfCompleted(this, new A_LstPMETaxProfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pack.tuxsalt_typedef.salt11")]
    public partial class D_InsPMGwRec {
        
        private fml32_D_InsPMGwRec_In inbufField;
        
        /// <remarks/>
        public fml32_D_InsPMGwRec_In inbuf {
            get {
                return this.inbufField;
            }
            set {
                this.inbufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pack.tuxsalt_typedef.salt11")]
    public partial class fml32_D_InsPMGwRec_In {
        
        private string pM_SERVICE_OPTIONField;
        
        private string pM_BILLING_ACC_NUMField;
        
        private string[] pM_MOBILE_NUMField;
        
        private System.DateTime[] pM_PAYMENT_DATField;
        
        private double[] pM_PAID_MNYField;
        
        private string[] pM_INVOICE_NUMField;
        
        private double[] pM_RECEIPT_IDField;
        
        private System.DateTime[] pM_RECEIPT_DATField;
        
        private double[] pM_RECEIPT_TOTAL_MNYField;
        
        private string[] pM_AIS_REFField;
        
        private string pM_PAY_FOR_CODEField;
        
        private string[] pM_SUBPAY_FOR_CODEField;
        
        private long[] pM_PAYMENT_CHANNEL_IDField;
        
        private double[] pM_PAYMENT_METHOD_IDField;
        
        private long[] pM_BANK_CODEField;
        
        private long[] pM_BRANCH_CODEField;
        
        private string pM_TRANS_FLAGField;
        
        /// <remarks/>
        public string PM_SERVICE_OPTION {
            get {
                return this.pM_SERVICE_OPTIONField;
            }
            set {
                this.pM_SERVICE_OPTIONField = value;
            }
        }
        
        /// <remarks/>
        public string PM_BILLING_ACC_NUM {
            get {
                return this.pM_BILLING_ACC_NUMField;
            }
            set {
                this.pM_BILLING_ACC_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_MOBILE_NUM")]
        public string[] PM_MOBILE_NUM {
            get {
                return this.pM_MOBILE_NUMField;
            }
            set {
                this.pM_MOBILE_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_PAYMENT_DAT", DataType="date")]
        public System.DateTime[] PM_PAYMENT_DAT {
            get {
                return this.pM_PAYMENT_DATField;
            }
            set {
                this.pM_PAYMENT_DATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_PAID_MNY")]
        public double[] PM_PAID_MNY {
            get {
                return this.pM_PAID_MNYField;
            }
            set {
                this.pM_PAID_MNYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_INVOICE_NUM")]
        public string[] PM_INVOICE_NUM {
            get {
                return this.pM_INVOICE_NUMField;
            }
            set {
                this.pM_INVOICE_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_RECEIPT_ID")]
        public double[] PM_RECEIPT_ID {
            get {
                return this.pM_RECEIPT_IDField;
            }
            set {
                this.pM_RECEIPT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_RECEIPT_DAT", DataType="date")]
        public System.DateTime[] PM_RECEIPT_DAT {
            get {
                return this.pM_RECEIPT_DATField;
            }
            set {
                this.pM_RECEIPT_DATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_RECEIPT_TOTAL_MNY")]
        public double[] PM_RECEIPT_TOTAL_MNY {
            get {
                return this.pM_RECEIPT_TOTAL_MNYField;
            }
            set {
                this.pM_RECEIPT_TOTAL_MNYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_AIS_REF")]
        public string[] PM_AIS_REF {
            get {
                return this.pM_AIS_REFField;
            }
            set {
                this.pM_AIS_REFField = value;
            }
        }
        
        /// <remarks/>
        public string PM_PAY_FOR_CODE {
            get {
                return this.pM_PAY_FOR_CODEField;
            }
            set {
                this.pM_PAY_FOR_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_SUBPAY_FOR_CODE")]
        public string[] PM_SUBPAY_FOR_CODE {
            get {
                return this.pM_SUBPAY_FOR_CODEField;
            }
            set {
                this.pM_SUBPAY_FOR_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_PAYMENT_CHANNEL_ID")]
        public long[] PM_PAYMENT_CHANNEL_ID {
            get {
                return this.pM_PAYMENT_CHANNEL_IDField;
            }
            set {
                this.pM_PAYMENT_CHANNEL_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_PAYMENT_METHOD_ID")]
        public double[] PM_PAYMENT_METHOD_ID {
            get {
                return this.pM_PAYMENT_METHOD_IDField;
            }
            set {
                this.pM_PAYMENT_METHOD_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_BANK_CODE")]
        public long[] PM_BANK_CODE {
            get {
                return this.pM_BANK_CODEField;
            }
            set {
                this.pM_BANK_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_BRANCH_CODE")]
        public long[] PM_BRANCH_CODE {
            get {
                return this.pM_BRANCH_CODEField;
            }
            set {
                this.pM_BRANCH_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string PM_TRANS_FLAG {
            get {
                return this.pM_TRANS_FLAGField;
            }
            set {
                this.pM_TRANS_FLAGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pack.tuxsalt_typedef.salt11")]
    public partial class fml32_A_LstPMETaxProf_Out {
        
        private string[] pM_BILLING_ACC_NUMField;
        
        private long pM_PAYMENT_CHANNEL_IDField;
        
        private bool pM_PAYMENT_CHANNEL_IDFieldSpecified;
        
        private string[] pM_ETAX_FLAGField;
        
        private string pM_TUX_CODEField;
        
        private string pM_TUX_MSGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_BILLING_ACC_NUM")]
        public string[] PM_BILLING_ACC_NUM {
            get {
                return this.pM_BILLING_ACC_NUMField;
            }
            set {
                this.pM_BILLING_ACC_NUMField = value;
            }
        }
        
        /// <remarks/>
        public long PM_PAYMENT_CHANNEL_ID {
            get {
                return this.pM_PAYMENT_CHANNEL_IDField;
            }
            set {
                this.pM_PAYMENT_CHANNEL_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PM_PAYMENT_CHANNEL_IDSpecified {
            get {
                return this.pM_PAYMENT_CHANNEL_IDFieldSpecified;
            }
            set {
                this.pM_PAYMENT_CHANNEL_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_ETAX_FLAG")]
        public string[] PM_ETAX_FLAG {
            get {
                return this.pM_ETAX_FLAGField;
            }
            set {
                this.pM_ETAX_FLAGField = value;
            }
        }
        
        /// <remarks/>
        public string PM_TUX_CODE {
            get {
                return this.pM_TUX_CODEField;
            }
            set {
                this.pM_TUX_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string PM_TUX_MSG {
            get {
                return this.pM_TUX_MSGField;
            }
            set {
                this.pM_TUX_MSGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pack.tuxsalt_typedef.salt11")]
    public partial class fml32_A_LstPMETaxProf_In {
        
        private string pM_SERVICE_OPTIONField;
        
        private string[] pM_BILLING_ACC_NUMField;
        
        private long pM_PAYMENT_CHANNEL_IDField;
        
        /// <remarks/>
        public string PM_SERVICE_OPTION {
            get {
                return this.pM_SERVICE_OPTIONField;
            }
            set {
                this.pM_SERVICE_OPTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_BILLING_ACC_NUM")]
        public string[] PM_BILLING_ACC_NUM {
            get {
                return this.pM_BILLING_ACC_NUMField;
            }
            set {
                this.pM_BILLING_ACC_NUMField = value;
            }
        }
        
        /// <remarks/>
        public long PM_PAYMENT_CHANNEL_ID {
            get {
                return this.pM_PAYMENT_CHANNEL_IDField;
            }
            set {
                this.pM_PAYMENT_CHANNEL_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pack.tuxsalt_typedef.salt11")]
    public partial class fml32_A_LstPMOrder_Out {
        
        private string[] pM_CODEField;
        
        private string[] pM_ROW_IDField;
        
        private string[] pM_ORDER_NUMBERField;
        
        private string[] pM_ORDER_DTField;
        
        private string[] pM_ORDER_SALES_ORDER_TYPEField;
        
        private string[] pM_ITEM_SERVICE_NUMField;
        
        private double[] pM_ITEM_BASE_PRICEField;
        
        private double[] pM_ITEM_DISCOUNT_AMTField;
        
        private string[] pM_ITEM_SIEBEL_PROD_IDField;
        
        private string[] pM_BILL_SOURCE_CDField;
        
        private string[] pM_INVOICING_CO_IDField;
        
        private double[] pM_VAT_MNYField;
        
        private string pM_TUX_CODEField;
        
        private string pM_TUX_MSGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_CODE")]
        public string[] PM_CODE {
            get {
                return this.pM_CODEField;
            }
            set {
                this.pM_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_ROW_ID")]
        public string[] PM_ROW_ID {
            get {
                return this.pM_ROW_IDField;
            }
            set {
                this.pM_ROW_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_ORDER_NUMBER")]
        public string[] PM_ORDER_NUMBER {
            get {
                return this.pM_ORDER_NUMBERField;
            }
            set {
                this.pM_ORDER_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_ORDER_DT")]
        public string[] PM_ORDER_DT {
            get {
                return this.pM_ORDER_DTField;
            }
            set {
                this.pM_ORDER_DTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_ORDER_SALES_ORDER_TYPE")]
        public string[] PM_ORDER_SALES_ORDER_TYPE {
            get {
                return this.pM_ORDER_SALES_ORDER_TYPEField;
            }
            set {
                this.pM_ORDER_SALES_ORDER_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_ITEM_SERVICE_NUM")]
        public string[] PM_ITEM_SERVICE_NUM {
            get {
                return this.pM_ITEM_SERVICE_NUMField;
            }
            set {
                this.pM_ITEM_SERVICE_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_ITEM_BASE_PRICE")]
        public double[] PM_ITEM_BASE_PRICE {
            get {
                return this.pM_ITEM_BASE_PRICEField;
            }
            set {
                this.pM_ITEM_BASE_PRICEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_ITEM_DISCOUNT_AMT")]
        public double[] PM_ITEM_DISCOUNT_AMT {
            get {
                return this.pM_ITEM_DISCOUNT_AMTField;
            }
            set {
                this.pM_ITEM_DISCOUNT_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_ITEM_SIEBEL_PROD_ID")]
        public string[] PM_ITEM_SIEBEL_PROD_ID {
            get {
                return this.pM_ITEM_SIEBEL_PROD_IDField;
            }
            set {
                this.pM_ITEM_SIEBEL_PROD_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_BILL_SOURCE_CD")]
        public string[] PM_BILL_SOURCE_CD {
            get {
                return this.pM_BILL_SOURCE_CDField;
            }
            set {
                this.pM_BILL_SOURCE_CDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_INVOICING_CO_ID")]
        public string[] PM_INVOICING_CO_ID {
            get {
                return this.pM_INVOICING_CO_IDField;
            }
            set {
                this.pM_INVOICING_CO_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_VAT_MNY")]
        public double[] PM_VAT_MNY {
            get {
                return this.pM_VAT_MNYField;
            }
            set {
                this.pM_VAT_MNYField = value;
            }
        }
        
        /// <remarks/>
        public string PM_TUX_CODE {
            get {
                return this.pM_TUX_CODEField;
            }
            set {
                this.pM_TUX_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string PM_TUX_MSG {
            get {
                return this.pM_TUX_MSGField;
            }
            set {
                this.pM_TUX_MSGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pack.tuxsalt_typedef.salt11")]
    public partial class fml32_A_LstPMOrder_In {
        
        private string pM_SERVICE_OPTIONField;
        
        private string pM_BILL_ACCNT_NUMField;
        
        private string[] pM_ORDER_NUMBERField;
        
        private string pM_MODULE_CODEField;
        
        /// <remarks/>
        public string PM_SERVICE_OPTION {
            get {
                return this.pM_SERVICE_OPTIONField;
            }
            set {
                this.pM_SERVICE_OPTIONField = value;
            }
        }
        
        /// <remarks/>
        public string PM_BILL_ACCNT_NUM {
            get {
                return this.pM_BILL_ACCNT_NUMField;
            }
            set {
                this.pM_BILL_ACCNT_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_ORDER_NUMBER")]
        public string[] PM_ORDER_NUMBER {
            get {
                return this.pM_ORDER_NUMBERField;
            }
            set {
                this.pM_ORDER_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        public string PM_MODULE_CODE {
            get {
                return this.pM_MODULE_CODEField;
            }
            set {
                this.pM_MODULE_CODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pack.tuxsalt_typedef.salt11")]
    public partial class fml32_A_ConfPMOrder_Out {
        
        private double[] pM_RECEIPT_IDField;
        
        private string[] pM_RECEIPT_NUMField;
        
        private string[] pM_BILLING_ACC_NUMField;
        
        private double[] pM_TAX_MNYField;
        
        private double[] pM_RECEIPT_TOT_MNYField;
        
        private string pM_TUX_CODEField;
        
        private string pM_TUX_MSGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_RECEIPT_ID")]
        public double[] PM_RECEIPT_ID {
            get {
                return this.pM_RECEIPT_IDField;
            }
            set {
                this.pM_RECEIPT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_RECEIPT_NUM")]
        public string[] PM_RECEIPT_NUM {
            get {
                return this.pM_RECEIPT_NUMField;
            }
            set {
                this.pM_RECEIPT_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_BILLING_ACC_NUM")]
        public string[] PM_BILLING_ACC_NUM {
            get {
                return this.pM_BILLING_ACC_NUMField;
            }
            set {
                this.pM_BILLING_ACC_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_TAX_MNY")]
        public double[] PM_TAX_MNY {
            get {
                return this.pM_TAX_MNYField;
            }
            set {
                this.pM_TAX_MNYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_RECEIPT_TOT_MNY")]
        public double[] PM_RECEIPT_TOT_MNY {
            get {
                return this.pM_RECEIPT_TOT_MNYField;
            }
            set {
                this.pM_RECEIPT_TOT_MNYField = value;
            }
        }
        
        /// <remarks/>
        public string PM_TUX_CODE {
            get {
                return this.pM_TUX_CODEField;
            }
            set {
                this.pM_TUX_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string PM_TUX_MSG {
            get {
                return this.pM_TUX_MSGField;
            }
            set {
                this.pM_TUX_MSGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pack.tuxsalt_typedef.salt11")]
    public partial class fml32_A_ConfPMOrder_In {
        
        private string pM_SERVICE_OPTIONField;
        
        private long pM_RECEIPT_LOCATIONField;
        
        private long pM_PAYMENT_CHANNEL_IDField;
        
        private long pM_SHIFT_NUMField;
        
        private bool pM_SHIFT_NUMFieldSpecified;
        
        private string pM_TERMINAL_IDField;
        
        private double pM_ADJUST_MNYField;
        
        private string[] pM_BILLING_ACC_NUMField;
        
        private string[] pM_MOBILE_NUMField;
        
        private string[] pM_RECEIPT_CO_IDField;
        
        private string[] pM_OTC_ROWIDField;
        
        private double[] pM_VAT_MNYField;
        
        private double[] pM_PAID_TOT_MNYField;
        
        private string pM_RECEIPT_MODEField;
        
        private string pM_NEXT_BILL_FLAGField;
        
        private string pM_PRINT_FLAGField;
        
        private string pM_USER_IDField;
        
        private long[] pM_PAYMENT_METHOD_IDField;
        
        private long[] pM_BANK_CODEField;
        
        private long[] pM_BRANCH_CODEField;
        
        private string[] pM_CREDIT_CARD_TYPEField;
        
        private string[] pM_DOC_NUMField;
        
        private string[] pM_DOC_DATField;
        
        private double pM_TAX_MNYField;
        
        private double[] pM_PAID_MNYField;
        
        private string pM_CHANNEL_DESC_ENGField;
        
        private string pM_TRAN_IDField;
        
        /// <remarks/>
        public string PM_SERVICE_OPTION {
            get {
                return this.pM_SERVICE_OPTIONField;
            }
            set {
                this.pM_SERVICE_OPTIONField = value;
            }
        }
        
        /// <remarks/>
        public long PM_RECEIPT_LOCATION {
            get {
                return this.pM_RECEIPT_LOCATIONField;
            }
            set {
                this.pM_RECEIPT_LOCATIONField = value;
            }
        }
        
        /// <remarks/>
        public long PM_PAYMENT_CHANNEL_ID {
            get {
                return this.pM_PAYMENT_CHANNEL_IDField;
            }
            set {
                this.pM_PAYMENT_CHANNEL_IDField = value;
            }
        }
        
        /// <remarks/>
        public long PM_SHIFT_NUM {
            get {
                return this.pM_SHIFT_NUMField;
            }
            set {
                this.pM_SHIFT_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PM_SHIFT_NUMSpecified {
            get {
                return this.pM_SHIFT_NUMFieldSpecified;
            }
            set {
                this.pM_SHIFT_NUMFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string PM_TERMINAL_ID {
            get {
                return this.pM_TERMINAL_IDField;
            }
            set {
                this.pM_TERMINAL_IDField = value;
            }
        }
        
        /// <remarks/>
        public double PM_ADJUST_MNY {
            get {
                return this.pM_ADJUST_MNYField;
            }
            set {
                this.pM_ADJUST_MNYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_BILLING_ACC_NUM")]
        public string[] PM_BILLING_ACC_NUM {
            get {
                return this.pM_BILLING_ACC_NUMField;
            }
            set {
                this.pM_BILLING_ACC_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_MOBILE_NUM")]
        public string[] PM_MOBILE_NUM {
            get {
                return this.pM_MOBILE_NUMField;
            }
            set {
                this.pM_MOBILE_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_RECEIPT_CO_ID")]
        public string[] PM_RECEIPT_CO_ID {
            get {
                return this.pM_RECEIPT_CO_IDField;
            }
            set {
                this.pM_RECEIPT_CO_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_OTC_ROWID")]
        public string[] PM_OTC_ROWID {
            get {
                return this.pM_OTC_ROWIDField;
            }
            set {
                this.pM_OTC_ROWIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_VAT_MNY")]
        public double[] PM_VAT_MNY {
            get {
                return this.pM_VAT_MNYField;
            }
            set {
                this.pM_VAT_MNYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_PAID_TOT_MNY")]
        public double[] PM_PAID_TOT_MNY {
            get {
                return this.pM_PAID_TOT_MNYField;
            }
            set {
                this.pM_PAID_TOT_MNYField = value;
            }
        }
        
        /// <remarks/>
        public string PM_RECEIPT_MODE {
            get {
                return this.pM_RECEIPT_MODEField;
            }
            set {
                this.pM_RECEIPT_MODEField = value;
            }
        }
        
        /// <remarks/>
        public string PM_NEXT_BILL_FLAG {
            get {
                return this.pM_NEXT_BILL_FLAGField;
            }
            set {
                this.pM_NEXT_BILL_FLAGField = value;
            }
        }
        
        /// <remarks/>
        public string PM_PRINT_FLAG {
            get {
                return this.pM_PRINT_FLAGField;
            }
            set {
                this.pM_PRINT_FLAGField = value;
            }
        }
        
        /// <remarks/>
        public string PM_USER_ID {
            get {
                return this.pM_USER_IDField;
            }
            set {
                this.pM_USER_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_PAYMENT_METHOD_ID")]
        public long[] PM_PAYMENT_METHOD_ID {
            get {
                return this.pM_PAYMENT_METHOD_IDField;
            }
            set {
                this.pM_PAYMENT_METHOD_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_BANK_CODE")]
        public long[] PM_BANK_CODE {
            get {
                return this.pM_BANK_CODEField;
            }
            set {
                this.pM_BANK_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_BRANCH_CODE")]
        public long[] PM_BRANCH_CODE {
            get {
                return this.pM_BRANCH_CODEField;
            }
            set {
                this.pM_BRANCH_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_CREDIT_CARD_TYPE")]
        public string[] PM_CREDIT_CARD_TYPE {
            get {
                return this.pM_CREDIT_CARD_TYPEField;
            }
            set {
                this.pM_CREDIT_CARD_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_DOC_NUM")]
        public string[] PM_DOC_NUM {
            get {
                return this.pM_DOC_NUMField;
            }
            set {
                this.pM_DOC_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_DOC_DAT")]
        public string[] PM_DOC_DAT {
            get {
                return this.pM_DOC_DATField;
            }
            set {
                this.pM_DOC_DATField = value;
            }
        }
        
        /// <remarks/>
        public double PM_TAX_MNY {
            get {
                return this.pM_TAX_MNYField;
            }
            set {
                this.pM_TAX_MNYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_PAID_MNY")]
        public double[] PM_PAID_MNY {
            get {
                return this.pM_PAID_MNYField;
            }
            set {
                this.pM_PAID_MNYField = value;
            }
        }
        
        /// <remarks/>
        public string PM_CHANNEL_DESC_ENG {
            get {
                return this.pM_CHANNEL_DESC_ENGField;
            }
            set {
                this.pM_CHANNEL_DESC_ENGField = value;
            }
        }
        
        /// <remarks/>
        public string PM_TRAN_ID {
            get {
                return this.pM_TRAN_IDField;
            }
            set {
                this.pM_TRAN_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pack.tuxsalt_typedef.salt11")]
    public partial class fml32_A_ConfPMPay_Out {
        
        private double[] pM_RECEIPT_IDField;
        
        private string[] pM_RECEIPT_NUMField;
        
        private string[] pM_BILLING_ACC_NUMField;
        
        private double[] pM_RECEIPT_TOT_MNYField;
        
        private double[] pM_TAX_MNYField;
        
        private string pM_TUX_CODEField;
        
        private string pM_TUX_MSGField;
        
        private string pM_USER_ERR_MSGField;
        
        private string pM_SRV_ERRORField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_RECEIPT_ID")]
        public double[] PM_RECEIPT_ID {
            get {
                return this.pM_RECEIPT_IDField;
            }
            set {
                this.pM_RECEIPT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_RECEIPT_NUM")]
        public string[] PM_RECEIPT_NUM {
            get {
                return this.pM_RECEIPT_NUMField;
            }
            set {
                this.pM_RECEIPT_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_BILLING_ACC_NUM")]
        public string[] PM_BILLING_ACC_NUM {
            get {
                return this.pM_BILLING_ACC_NUMField;
            }
            set {
                this.pM_BILLING_ACC_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_RECEIPT_TOT_MNY")]
        public double[] PM_RECEIPT_TOT_MNY {
            get {
                return this.pM_RECEIPT_TOT_MNYField;
            }
            set {
                this.pM_RECEIPT_TOT_MNYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_TAX_MNY")]
        public double[] PM_TAX_MNY {
            get {
                return this.pM_TAX_MNYField;
            }
            set {
                this.pM_TAX_MNYField = value;
            }
        }
        
        /// <remarks/>
        public string PM_TUX_CODE {
            get {
                return this.pM_TUX_CODEField;
            }
            set {
                this.pM_TUX_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string PM_TUX_MSG {
            get {
                return this.pM_TUX_MSGField;
            }
            set {
                this.pM_TUX_MSGField = value;
            }
        }
        
        /// <remarks/>
        public string PM_USER_ERR_MSG {
            get {
                return this.pM_USER_ERR_MSGField;
            }
            set {
                this.pM_USER_ERR_MSGField = value;
            }
        }
        
        /// <remarks/>
        public string PM_SRV_ERROR {
            get {
                return this.pM_SRV_ERRORField;
            }
            set {
                this.pM_SRV_ERRORField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pack.tuxsalt_typedef.salt11")]
    public partial class fml32_A_ConfPMPay_In {
        
        private string pM_MOBLIE_NUMField;
        
        private string pM_BILLING_ACC_NUMField;
        
        private string[] pM_STATUS_CDField;
        
        private double pM_PAID_AMTField;
        
        private double pM_TAX_AMTField;
        
        private bool pM_TAX_AMTFieldSpecified;
        
        private long pM_RECEIPT_LOCATIONField;
        
        private long pM_PAYMENT_CHANNEL_IDField;
        
        private long pM_SHIFT_NUMField;
        
        private bool pM_SHIFT_NUMFieldSpecified;
        
        private string pM_TERMINAL_IDField;
        
        private string pM_USER_IDField;
        
        private string pM_NEXT_BILL_FLAGField;
        
        private double pM_PAYMENT_METHOD_IDField;
        
        private long pM_BANK_CODEField;
        
        private bool pM_BANK_CODEFieldSpecified;
        
        private long pM_BRANCH_CODEField;
        
        private bool pM_BRANCH_CODEFieldSpecified;
        
        private string pM_POST_CODEField;
        
        private string pM_CREDIT_CARD_TYPEField;
        
        private string pM_DOC_NUMField;
        
        private string pM_DOC_DATField;
        
        private long pM_PRINT_FLAGField;
        
        private string[] pM_INVOICE_NUMField;
        
        private double pM_OVER_USAGE_MNYField;
        
        private bool pM_OVER_USAGE_MNYFieldSpecified;
        
        private string pM_FLAGField;
        
        private string pM_AIS_REFField;
        
        private string pM_TRAN_IDField;
        
        private string pM_SUB_CHANNELField;
        
        /// <remarks/>
        public string PM_MOBLIE_NUM {
            get {
                return this.pM_MOBLIE_NUMField;
            }
            set {
                this.pM_MOBLIE_NUMField = value;
            }
        }
        
        /// <remarks/>
        public string PM_BILLING_ACC_NUM {
            get {
                return this.pM_BILLING_ACC_NUMField;
            }
            set {
                this.pM_BILLING_ACC_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_STATUS_CD")]
        public string[] PM_STATUS_CD {
            get {
                return this.pM_STATUS_CDField;
            }
            set {
                this.pM_STATUS_CDField = value;
            }
        }
        
        /// <remarks/>
        public double PM_PAID_AMT {
            get {
                return this.pM_PAID_AMTField;
            }
            set {
                this.pM_PAID_AMTField = value;
            }
        }
        
        /// <remarks/>
        public double PM_TAX_AMT {
            get {
                return this.pM_TAX_AMTField;
            }
            set {
                this.pM_TAX_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PM_TAX_AMTSpecified {
            get {
                return this.pM_TAX_AMTFieldSpecified;
            }
            set {
                this.pM_TAX_AMTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long PM_RECEIPT_LOCATION {
            get {
                return this.pM_RECEIPT_LOCATIONField;
            }
            set {
                this.pM_RECEIPT_LOCATIONField = value;
            }
        }
        
        /// <remarks/>
        public long PM_PAYMENT_CHANNEL_ID {
            get {
                return this.pM_PAYMENT_CHANNEL_IDField;
            }
            set {
                this.pM_PAYMENT_CHANNEL_IDField = value;
            }
        }
        
        /// <remarks/>
        public long PM_SHIFT_NUM {
            get {
                return this.pM_SHIFT_NUMField;
            }
            set {
                this.pM_SHIFT_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PM_SHIFT_NUMSpecified {
            get {
                return this.pM_SHIFT_NUMFieldSpecified;
            }
            set {
                this.pM_SHIFT_NUMFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string PM_TERMINAL_ID {
            get {
                return this.pM_TERMINAL_IDField;
            }
            set {
                this.pM_TERMINAL_IDField = value;
            }
        }
        
        /// <remarks/>
        public string PM_USER_ID {
            get {
                return this.pM_USER_IDField;
            }
            set {
                this.pM_USER_IDField = value;
            }
        }
        
        /// <remarks/>
        public string PM_NEXT_BILL_FLAG {
            get {
                return this.pM_NEXT_BILL_FLAGField;
            }
            set {
                this.pM_NEXT_BILL_FLAGField = value;
            }
        }
        
        /// <remarks/>
        public double PM_PAYMENT_METHOD_ID {
            get {
                return this.pM_PAYMENT_METHOD_IDField;
            }
            set {
                this.pM_PAYMENT_METHOD_IDField = value;
            }
        }
        
        /// <remarks/>
        public long PM_BANK_CODE {
            get {
                return this.pM_BANK_CODEField;
            }
            set {
                this.pM_BANK_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PM_BANK_CODESpecified {
            get {
                return this.pM_BANK_CODEFieldSpecified;
            }
            set {
                this.pM_BANK_CODEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long PM_BRANCH_CODE {
            get {
                return this.pM_BRANCH_CODEField;
            }
            set {
                this.pM_BRANCH_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PM_BRANCH_CODESpecified {
            get {
                return this.pM_BRANCH_CODEFieldSpecified;
            }
            set {
                this.pM_BRANCH_CODEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string PM_POST_CODE {
            get {
                return this.pM_POST_CODEField;
            }
            set {
                this.pM_POST_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string PM_CREDIT_CARD_TYPE {
            get {
                return this.pM_CREDIT_CARD_TYPEField;
            }
            set {
                this.pM_CREDIT_CARD_TYPEField = value;
            }
        }
        
        /// <remarks/>
        public string PM_DOC_NUM {
            get {
                return this.pM_DOC_NUMField;
            }
            set {
                this.pM_DOC_NUMField = value;
            }
        }
        
        /// <remarks/>
        public string PM_DOC_DAT {
            get {
                return this.pM_DOC_DATField;
            }
            set {
                this.pM_DOC_DATField = value;
            }
        }
        
        /// <remarks/>
        public long PM_PRINT_FLAG {
            get {
                return this.pM_PRINT_FLAGField;
            }
            set {
                this.pM_PRINT_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_INVOICE_NUM")]
        public string[] PM_INVOICE_NUM {
            get {
                return this.pM_INVOICE_NUMField;
            }
            set {
                this.pM_INVOICE_NUMField = value;
            }
        }
        
        /// <remarks/>
        public double PM_OVER_USAGE_MNY {
            get {
                return this.pM_OVER_USAGE_MNYField;
            }
            set {
                this.pM_OVER_USAGE_MNYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PM_OVER_USAGE_MNYSpecified {
            get {
                return this.pM_OVER_USAGE_MNYFieldSpecified;
            }
            set {
                this.pM_OVER_USAGE_MNYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string PM_FLAG {
            get {
                return this.pM_FLAGField;
            }
            set {
                this.pM_FLAGField = value;
            }
        }
        
        /// <remarks/>
        public string PM_AIS_REF {
            get {
                return this.pM_AIS_REFField;
            }
            set {
                this.pM_AIS_REFField = value;
            }
        }
        
        /// <remarks/>
        public string PM_TRAN_ID {
            get {
                return this.pM_TRAN_IDField;
            }
            set {
                this.pM_TRAN_IDField = value;
            }
        }
        
        /// <remarks/>
        public string PM_SUB_CHANNEL {
            get {
                return this.pM_SUB_CHANNELField;
            }
            set {
                this.pM_SUB_CHANNELField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pack.tuxsalt_typedef.salt11")]
    public partial class fml32_A_LstPMMobDtl_Out {
        
        private double[] pM_SUM_INVOICEField;
        
        private double[] pM_EXCESS_PAYMENT_MNYField;
        
        private double[] pM_ACCOUNT_TOTAL_BALANCE_MNYField;
        
        private string[] pM_BILL_SOURCE_CDField;
        
        private string[] pM_BILLING_ACC_NUMField;
        
        private string[] pM_NAMEField;
        
        private string[] pM_STATUS_CDField;
        
        private string[] pM_X_STATUS_DATEField;
        
        private string[] pM_LAST_DUE_DATEField;
        
        private double[] pM_INVOICE_INC_VAT_MNYField;
        
        private double[] pM_INVOICE_NON_VAT_MNYField;
        
        private double[] pM_INVOICE_TOTAL_MNYField;
        
        private double[] pM_INVOICE_VAT_MNYField;
        
        private double[] pM_TOTAL_BALANCE_MNYField;
        
        private double[] pM_MONTHLY_FEE_MNYField;
        
        private double[] pM_MONTHLY_FEE_WT_RATEField;
        
        private double[] pM_SERVICE_CHARGE_MNYField;
        
        private double[] pM_SERVICE_CHARGE_WT_RATEField;
        
        private string[] pM_BILL_END_DATField;
        
        private string[] pM_BILL_START_DATField;
        
        private string[] pM_INVOICE_DATField;
        
        private string[] pM_INVOICE_NUMField;
        
        private string[] pM_INVOICING_CO_IDField;
        
        private string[] pM_PAYMENT_DUE_DATField;
        
        private double[] pM_OTC_DISCOUNT_MNYField;
        
        private double[] pM_OTC_DISCOUNT_VAT_MNYField;
        
        private double[] pM_OTC_VAT_MNYField;
        
        private double[] pM_OTC_INC_VAT_MNYField;
        
        private string[] pM_ORDER_DTField;
        
        private string[] pM_ORDER_NUMBERField;
        
        private string[] pM_ORDER_SALES_ORDER_TYPEField;
        
        private string[] pM_ROW_IDField;
        
        private long[] pM_OVER_USAGEField;
        
        private long[] pM_NO_DC_MOBField;
        
        private double[] pM_PAY_AMOUNTField;
        
        private double[] pM_MIN_ADV_PAYMTField;
        
        private string[] pM_FML_STR1Field;
        
        private string[] pM_MOBILE_FLAGField;
        
        private string[] pM_TAX_NUMField;
        
        private string pM_TUX_CODEField;
        
        private string pM_TUX_MSGField;
        
        private string pM_USER_ERR_MSGField;
        
        private string pM_SRV_ERRORField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_SUM_INVOICE")]
        public double[] PM_SUM_INVOICE {
            get {
                return this.pM_SUM_INVOICEField;
            }
            set {
                this.pM_SUM_INVOICEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_EXCESS_PAYMENT_MNY")]
        public double[] PM_EXCESS_PAYMENT_MNY {
            get {
                return this.pM_EXCESS_PAYMENT_MNYField;
            }
            set {
                this.pM_EXCESS_PAYMENT_MNYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_ACCOUNT_TOTAL_BALANCE_MNY")]
        public double[] PM_ACCOUNT_TOTAL_BALANCE_MNY {
            get {
                return this.pM_ACCOUNT_TOTAL_BALANCE_MNYField;
            }
            set {
                this.pM_ACCOUNT_TOTAL_BALANCE_MNYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_BILL_SOURCE_CD")]
        public string[] PM_BILL_SOURCE_CD {
            get {
                return this.pM_BILL_SOURCE_CDField;
            }
            set {
                this.pM_BILL_SOURCE_CDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_BILLING_ACC_NUM")]
        public string[] PM_BILLING_ACC_NUM {
            get {
                return this.pM_BILLING_ACC_NUMField;
            }
            set {
                this.pM_BILLING_ACC_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_NAME")]
        public string[] PM_NAME {
            get {
                return this.pM_NAMEField;
            }
            set {
                this.pM_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_STATUS_CD")]
        public string[] PM_STATUS_CD {
            get {
                return this.pM_STATUS_CDField;
            }
            set {
                this.pM_STATUS_CDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_X_STATUS_DATE")]
        public string[] PM_X_STATUS_DATE {
            get {
                return this.pM_X_STATUS_DATEField;
            }
            set {
                this.pM_X_STATUS_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_LAST_DUE_DATE")]
        public string[] PM_LAST_DUE_DATE {
            get {
                return this.pM_LAST_DUE_DATEField;
            }
            set {
                this.pM_LAST_DUE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_INVOICE_INC_VAT_MNY")]
        public double[] PM_INVOICE_INC_VAT_MNY {
            get {
                return this.pM_INVOICE_INC_VAT_MNYField;
            }
            set {
                this.pM_INVOICE_INC_VAT_MNYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_INVOICE_NON_VAT_MNY")]
        public double[] PM_INVOICE_NON_VAT_MNY {
            get {
                return this.pM_INVOICE_NON_VAT_MNYField;
            }
            set {
                this.pM_INVOICE_NON_VAT_MNYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_INVOICE_TOTAL_MNY")]
        public double[] PM_INVOICE_TOTAL_MNY {
            get {
                return this.pM_INVOICE_TOTAL_MNYField;
            }
            set {
                this.pM_INVOICE_TOTAL_MNYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_INVOICE_VAT_MNY")]
        public double[] PM_INVOICE_VAT_MNY {
            get {
                return this.pM_INVOICE_VAT_MNYField;
            }
            set {
                this.pM_INVOICE_VAT_MNYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_TOTAL_BALANCE_MNY")]
        public double[] PM_TOTAL_BALANCE_MNY {
            get {
                return this.pM_TOTAL_BALANCE_MNYField;
            }
            set {
                this.pM_TOTAL_BALANCE_MNYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_MONTHLY_FEE_MNY")]
        public double[] PM_MONTHLY_FEE_MNY {
            get {
                return this.pM_MONTHLY_FEE_MNYField;
            }
            set {
                this.pM_MONTHLY_FEE_MNYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_MONTHLY_FEE_WT_RATE")]
        public double[] PM_MONTHLY_FEE_WT_RATE {
            get {
                return this.pM_MONTHLY_FEE_WT_RATEField;
            }
            set {
                this.pM_MONTHLY_FEE_WT_RATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_SERVICE_CHARGE_MNY")]
        public double[] PM_SERVICE_CHARGE_MNY {
            get {
                return this.pM_SERVICE_CHARGE_MNYField;
            }
            set {
                this.pM_SERVICE_CHARGE_MNYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_SERVICE_CHARGE_WT_RATE")]
        public double[] PM_SERVICE_CHARGE_WT_RATE {
            get {
                return this.pM_SERVICE_CHARGE_WT_RATEField;
            }
            set {
                this.pM_SERVICE_CHARGE_WT_RATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_BILL_END_DAT")]
        public string[] PM_BILL_END_DAT {
            get {
                return this.pM_BILL_END_DATField;
            }
            set {
                this.pM_BILL_END_DATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_BILL_START_DAT")]
        public string[] PM_BILL_START_DAT {
            get {
                return this.pM_BILL_START_DATField;
            }
            set {
                this.pM_BILL_START_DATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_INVOICE_DAT")]
        public string[] PM_INVOICE_DAT {
            get {
                return this.pM_INVOICE_DATField;
            }
            set {
                this.pM_INVOICE_DATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_INVOICE_NUM")]
        public string[] PM_INVOICE_NUM {
            get {
                return this.pM_INVOICE_NUMField;
            }
            set {
                this.pM_INVOICE_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_INVOICING_CO_ID")]
        public string[] PM_INVOICING_CO_ID {
            get {
                return this.pM_INVOICING_CO_IDField;
            }
            set {
                this.pM_INVOICING_CO_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_PAYMENT_DUE_DAT")]
        public string[] PM_PAYMENT_DUE_DAT {
            get {
                return this.pM_PAYMENT_DUE_DATField;
            }
            set {
                this.pM_PAYMENT_DUE_DATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_OTC_DISCOUNT_MNY")]
        public double[] PM_OTC_DISCOUNT_MNY {
            get {
                return this.pM_OTC_DISCOUNT_MNYField;
            }
            set {
                this.pM_OTC_DISCOUNT_MNYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_OTC_DISCOUNT_VAT_MNY")]
        public double[] PM_OTC_DISCOUNT_VAT_MNY {
            get {
                return this.pM_OTC_DISCOUNT_VAT_MNYField;
            }
            set {
                this.pM_OTC_DISCOUNT_VAT_MNYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_OTC_VAT_MNY")]
        public double[] PM_OTC_VAT_MNY {
            get {
                return this.pM_OTC_VAT_MNYField;
            }
            set {
                this.pM_OTC_VAT_MNYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_OTC_INC_VAT_MNY")]
        public double[] PM_OTC_INC_VAT_MNY {
            get {
                return this.pM_OTC_INC_VAT_MNYField;
            }
            set {
                this.pM_OTC_INC_VAT_MNYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_ORDER_DT")]
        public string[] PM_ORDER_DT {
            get {
                return this.pM_ORDER_DTField;
            }
            set {
                this.pM_ORDER_DTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_ORDER_NUMBER")]
        public string[] PM_ORDER_NUMBER {
            get {
                return this.pM_ORDER_NUMBERField;
            }
            set {
                this.pM_ORDER_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_ORDER_SALES_ORDER_TYPE")]
        public string[] PM_ORDER_SALES_ORDER_TYPE {
            get {
                return this.pM_ORDER_SALES_ORDER_TYPEField;
            }
            set {
                this.pM_ORDER_SALES_ORDER_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_ROW_ID")]
        public string[] PM_ROW_ID {
            get {
                return this.pM_ROW_IDField;
            }
            set {
                this.pM_ROW_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_OVER_USAGE")]
        public long[] PM_OVER_USAGE {
            get {
                return this.pM_OVER_USAGEField;
            }
            set {
                this.pM_OVER_USAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_NO_DC_MOB")]
        public long[] PM_NO_DC_MOB {
            get {
                return this.pM_NO_DC_MOBField;
            }
            set {
                this.pM_NO_DC_MOBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_PAY_AMOUNT")]
        public double[] PM_PAY_AMOUNT {
            get {
                return this.pM_PAY_AMOUNTField;
            }
            set {
                this.pM_PAY_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_MIN_ADV_PAYMT")]
        public double[] PM_MIN_ADV_PAYMT {
            get {
                return this.pM_MIN_ADV_PAYMTField;
            }
            set {
                this.pM_MIN_ADV_PAYMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_FML_STR1")]
        public string[] PM_FML_STR1 {
            get {
                return this.pM_FML_STR1Field;
            }
            set {
                this.pM_FML_STR1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_MOBILE_FLAG")]
        public string[] PM_MOBILE_FLAG {
            get {
                return this.pM_MOBILE_FLAGField;
            }
            set {
                this.pM_MOBILE_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_TAX_NUM")]
        public string[] PM_TAX_NUM {
            get {
                return this.pM_TAX_NUMField;
            }
            set {
                this.pM_TAX_NUMField = value;
            }
        }
        
        /// <remarks/>
        public string PM_TUX_CODE {
            get {
                return this.pM_TUX_CODEField;
            }
            set {
                this.pM_TUX_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string PM_TUX_MSG {
            get {
                return this.pM_TUX_MSGField;
            }
            set {
                this.pM_TUX_MSGField = value;
            }
        }
        
        /// <remarks/>
        public string PM_USER_ERR_MSG {
            get {
                return this.pM_USER_ERR_MSGField;
            }
            set {
                this.pM_USER_ERR_MSGField = value;
            }
        }
        
        /// <remarks/>
        public string PM_SRV_ERROR {
            get {
                return this.pM_SRV_ERRORField;
            }
            set {
                this.pM_SRV_ERRORField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pack.tuxsalt_typedef.salt11")]
    public partial class fml32_A_LstPMMobDtl_In {
        
        private string[] pM_MOBLIE_NUMField;
        
        private string[] pM_BILLING_ACC_NUMField;
        
        private string[] pM_3G_FLAGField;
        
        private string[] pM_SUB_CHANNELField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_MOBLIE_NUM")]
        public string[] PM_MOBLIE_NUM {
            get {
                return this.pM_MOBLIE_NUMField;
            }
            set {
                this.pM_MOBLIE_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_BILLING_ACC_NUM")]
        public string[] PM_BILLING_ACC_NUM {
            get {
                return this.pM_BILLING_ACC_NUMField;
            }
            set {
                this.pM_BILLING_ACC_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_3G_FLAG")]
        public string[] PM_3G_FLAG {
            get {
                return this.pM_3G_FLAGField;
            }
            set {
                this.pM_3G_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PM_SUB_CHANNEL")]
        public string[] PM_SUB_CHANNEL {
            get {
                return this.pM_SUB_CHANNELField;
            }
            set {
                this.pM_SUB_CHANNELField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pack.tuxsalt_typedef.salt11")]
    public partial class fml32_D_InsPMGwRec_Out {
        
        private string pM_ERROR_CODEField;
        
        private string pM_ERROR_MESSAGEField;
        
        /// <remarks/>
        public string PM_ERROR_CODE {
            get {
                return this.pM_ERROR_CODEField;
            }
            set {
                this.pM_ERROR_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string PM_ERROR_MESSAGE {
            get {
                return this.pM_ERROR_MESSAGEField;
            }
            set {
                this.pM_ERROR_MESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pack.tuxsalt_typedef.salt11")]
    public partial class D_InsPMGwRecResponse {
        
        private fml32_D_InsPMGwRec_Out outbufField;
        
        /// <remarks/>
        public fml32_D_InsPMGwRec_Out outbuf {
            get {
                return this.outbufField;
            }
            set {
                this.outbufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pack.tuxsalt_typedef.salt11")]
    public partial class A_LstPMMobDtl {
        
        private fml32_A_LstPMMobDtl_In inbufField;
        
        /// <remarks/>
        public fml32_A_LstPMMobDtl_In inbuf {
            get {
                return this.inbufField;
            }
            set {
                this.inbufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pack.tuxsalt_typedef.salt11")]
    public partial class A_LstPMMobDtlResponse {
        
        private fml32_A_LstPMMobDtl_Out outbufField;
        
        /// <remarks/>
        public fml32_A_LstPMMobDtl_Out outbuf {
            get {
                return this.outbufField;
            }
            set {
                this.outbufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pack.tuxsalt_typedef.salt11")]
    public partial class A_ConfPMPay {
        
        private fml32_A_ConfPMPay_In inbufField;
        
        /// <remarks/>
        public fml32_A_ConfPMPay_In inbuf {
            get {
                return this.inbufField;
            }
            set {
                this.inbufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pack.tuxsalt_typedef.salt11")]
    public partial class A_ConfPMPayResponse {
        
        private fml32_A_ConfPMPay_Out outbufField;
        
        /// <remarks/>
        public fml32_A_ConfPMPay_Out outbuf {
            get {
                return this.outbufField;
            }
            set {
                this.outbufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pack.tuxsalt_typedef.salt11")]
    public partial class A_ConfPMOrder {
        
        private fml32_A_ConfPMOrder_In inbufField;
        
        /// <remarks/>
        public fml32_A_ConfPMOrder_In inbuf {
            get {
                return this.inbufField;
            }
            set {
                this.inbufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pack.tuxsalt_typedef.salt11")]
    public partial class A_ConfPMOrderResponse {
        
        private fml32_A_ConfPMOrder_Out outbufField;
        
        /// <remarks/>
        public fml32_A_ConfPMOrder_Out outbuf {
            get {
                return this.outbufField;
            }
            set {
                this.outbufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pack.tuxsalt_typedef.salt11")]
    public partial class A_LstPMOrder {
        
        private fml32_A_LstPMOrder_In inbufField;
        
        /// <remarks/>
        public fml32_A_LstPMOrder_In inbuf {
            get {
                return this.inbufField;
            }
            set {
                this.inbufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pack.tuxsalt_typedef.salt11")]
    public partial class A_LstPMOrderResponse {
        
        private fml32_A_LstPMOrder_Out outbufField;
        
        /// <remarks/>
        public fml32_A_LstPMOrder_Out outbuf {
            get {
                return this.outbufField;
            }
            set {
                this.outbufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pack.tuxsalt_typedef.salt11")]
    public partial class A_LstPMETaxProf {
        
        private fml32_A_LstPMETaxProf_In inbufField;
        
        /// <remarks/>
        public fml32_A_LstPMETaxProf_In inbuf {
            get {
                return this.inbufField;
            }
            set {
                this.inbufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pack.tuxsalt_typedef.salt11")]
    public partial class A_LstPMETaxProfResponse {
        
        private fml32_A_LstPMETaxProf_Out outbufField;
        
        /// <remarks/>
        public fml32_A_LstPMETaxProf_Out outbuf {
            get {
                return this.outbufField;
            }
            set {
                this.outbufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void D_InsPMGwRecCompletedEventHandler(object sender, D_InsPMGwRecCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class D_InsPMGwRecCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal D_InsPMGwRecCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public D_InsPMGwRecResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((D_InsPMGwRecResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void A_LstPMMobDtlCompletedEventHandler(object sender, A_LstPMMobDtlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class A_LstPMMobDtlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal A_LstPMMobDtlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public A_LstPMMobDtlResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((A_LstPMMobDtlResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void A_ConfPMPayCompletedEventHandler(object sender, A_ConfPMPayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class A_ConfPMPayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal A_ConfPMPayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public A_ConfPMPayResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((A_ConfPMPayResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void A_ConfPMOrderCompletedEventHandler(object sender, A_ConfPMOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class A_ConfPMOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal A_ConfPMOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public A_ConfPMOrderResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((A_ConfPMOrderResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void A_LstPMOrderCompletedEventHandler(object sender, A_LstPMOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class A_LstPMOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal A_LstPMOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public A_LstPMOrderResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((A_LstPMOrderResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void A_LstPMETaxProfCompletedEventHandler(object sender, A_LstPMETaxProfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class A_LstPMETaxProfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal A_LstPMETaxProfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public A_LstPMETaxProfResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((A_LstPMETaxProfResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591