//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WBBBusinessLayer.FBBSAPOnline1 {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IFBBSAPOnline", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RenewService))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SAPResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TerminateService))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstallationCost))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JoinOrder))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Register))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewRegistFOA))]
    public partial class FBBSAPOnline : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback NewRegistForSubmitFOAOperationCompleted;
        
        private System.Threading.SendOrPostCallback NewRegistOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback JoinOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback InstallationCostOperationCompleted;
        
        private System.Threading.SendOrPostCallback TerminateServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback RenewServiceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FBBSAPOnline() {
            this.Url = global::WBBBusinessLayer.Properties.Settings.Default.WBBBusinessLayer_FBBSAPOnline1_FBBSAPOnline;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event NewRegistForSubmitFOACompletedEventHandler NewRegistForSubmitFOACompleted;
        
        /// <remarks/>
        public event NewRegistOrderCompletedEventHandler NewRegistOrderCompleted;
        
        /// <remarks/>
        public event JoinOrderCompletedEventHandler JoinOrderCompleted;
        
        /// <remarks/>
        public event InstallationCostCompletedEventHandler InstallationCostCompleted;
        
        /// <remarks/>
        public event TerminateServiceCompletedEventHandler TerminateServiceCompleted;
        
        /// <remarks/>
        public event RenewServiceCompletedEventHandler RenewServiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFBBSAPOnline/NewRegistForSubmitFOA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NewRegistForSubmitFOAResponse NewRegistForSubmitFOA([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] NewRegistForSubmitFOAQuery query) {
            object[] results = this.Invoke("NewRegistForSubmitFOA", new object[] {
                        query});
            return ((NewRegistForSubmitFOAResponse)(results[0]));
        }
        
        /// <remarks/>
        public void NewRegistForSubmitFOAAsync(NewRegistForSubmitFOAQuery query) {
            this.NewRegistForSubmitFOAAsync(query, null);
        }
        
        /// <remarks/>
        public void NewRegistForSubmitFOAAsync(NewRegistForSubmitFOAQuery query, object userState) {
            if ((this.NewRegistForSubmitFOAOperationCompleted == null)) {
                this.NewRegistForSubmitFOAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNewRegistForSubmitFOAOperationCompleted);
            }
            this.InvokeAsync("NewRegistForSubmitFOA", new object[] {
                        query}, this.NewRegistForSubmitFOAOperationCompleted, userState);
        }
        
        private void OnNewRegistForSubmitFOAOperationCompleted(object arg) {
            if ((this.NewRegistForSubmitFOACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NewRegistForSubmitFOACompleted(this, new NewRegistForSubmitFOACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFBBSAPOnline/NewRegistOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NewRegisterResponse NewRegistOrder([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] NewRegisterQuery query) {
            object[] results = this.Invoke("NewRegistOrder", new object[] {
                        query});
            return ((NewRegisterResponse)(results[0]));
        }
        
        /// <remarks/>
        public void NewRegistOrderAsync(NewRegisterQuery query) {
            this.NewRegistOrderAsync(query, null);
        }
        
        /// <remarks/>
        public void NewRegistOrderAsync(NewRegisterQuery query, object userState) {
            if ((this.NewRegistOrderOperationCompleted == null)) {
                this.NewRegistOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNewRegistOrderOperationCompleted);
            }
            this.InvokeAsync("NewRegistOrder", new object[] {
                        query}, this.NewRegistOrderOperationCompleted, userState);
        }
        
        private void OnNewRegistOrderOperationCompleted(object arg) {
            if ((this.NewRegistOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NewRegistOrderCompleted(this, new NewRegistOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFBBSAPOnline/JoinOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public JoinOrderResponse JoinOrder([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] JoinOrderQuery query) {
            object[] results = this.Invoke("JoinOrder", new object[] {
                        query});
            return ((JoinOrderResponse)(results[0]));
        }
        
        /// <remarks/>
        public void JoinOrderAsync(JoinOrderQuery query) {
            this.JoinOrderAsync(query, null);
        }
        
        /// <remarks/>
        public void JoinOrderAsync(JoinOrderQuery query, object userState) {
            if ((this.JoinOrderOperationCompleted == null)) {
                this.JoinOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnJoinOrderOperationCompleted);
            }
            this.InvokeAsync("JoinOrder", new object[] {
                        query}, this.JoinOrderOperationCompleted, userState);
        }
        
        private void OnJoinOrderOperationCompleted(object arg) {
            if ((this.JoinOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.JoinOrderCompleted(this, new JoinOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFBBSAPOnline/InstallationCost", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public InstallationCostResponse InstallationCost([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] InstallationCostQuery query) {
            object[] results = this.Invoke("InstallationCost", new object[] {
                        query});
            return ((InstallationCostResponse)(results[0]));
        }
        
        /// <remarks/>
        public void InstallationCostAsync(InstallationCostQuery query) {
            this.InstallationCostAsync(query, null);
        }
        
        /// <remarks/>
        public void InstallationCostAsync(InstallationCostQuery query, object userState) {
            if ((this.InstallationCostOperationCompleted == null)) {
                this.InstallationCostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInstallationCostOperationCompleted);
            }
            this.InvokeAsync("InstallationCost", new object[] {
                        query}, this.InstallationCostOperationCompleted, userState);
        }
        
        private void OnInstallationCostOperationCompleted(object arg) {
            if ((this.InstallationCostCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InstallationCostCompleted(this, new InstallationCostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFBBSAPOnline/TerminateService", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TerminateServiceResponse TerminateService([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] TerminateServiceQuery query) {
            object[] results = this.Invoke("TerminateService", new object[] {
                        query});
            return ((TerminateServiceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void TerminateServiceAsync(TerminateServiceQuery query) {
            this.TerminateServiceAsync(query, null);
        }
        
        /// <remarks/>
        public void TerminateServiceAsync(TerminateServiceQuery query, object userState) {
            if ((this.TerminateServiceOperationCompleted == null)) {
                this.TerminateServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTerminateServiceOperationCompleted);
            }
            this.InvokeAsync("TerminateService", new object[] {
                        query}, this.TerminateServiceOperationCompleted, userState);
        }
        
        private void OnTerminateServiceOperationCompleted(object arg) {
            if ((this.TerminateServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TerminateServiceCompleted(this, new TerminateServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFBBSAPOnline/RenewService", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RenewServiceResponse RenewService([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RenewServiceQuery query) {
            object[] results = this.Invoke("RenewService", new object[] {
                        query});
            return ((RenewServiceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void RenewServiceAsync(RenewServiceQuery query) {
            this.RenewServiceAsync(query, null);
        }
        
        /// <remarks/>
        public void RenewServiceAsync(RenewServiceQuery query, object userState) {
            if ((this.RenewServiceOperationCompleted == null)) {
                this.RenewServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRenewServiceOperationCompleted);
            }
            this.InvokeAsync("RenewService", new object[] {
                        query}, this.RenewServiceOperationCompleted, userState);
        }
        
        private void OnRenewServiceOperationCompleted(object arg) {
            if ((this.RenewServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RenewServiceCompleted(this, new RenewServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WBBContract.Queries.ExWebServices")]
    public partial class NewRegistForSubmitFOAQuery : NewRegistFOA {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewRegistForSubmitFOAQuery))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WBBEntity.PanelModels.ExWebServiceModels")]
    public partial class NewRegistFOA {
        
        private string access_NoField;
        
        private string bUILDING_NAMEField;
        
        private string fOA_Submit_dateField;
        
        private string mobile_ContactField;
        
        private string oLT_NAMEField;
        
        private string orderNumberField;
        
        private string orderTypeField;
        
        private NewRegistFOAProductList[] productListField;
        
        private string productNameField;
        
        private string rejectReasonField;
        
        private NewRegistFOAServiceList[] serviceListField;
        
        private string subcontractorCodeField;
        
        private string subcontractorNameField;
        
        private string submitFlagField;
        
        private string post_DateField;
        
        private string address_IDField;
        
        private string oRG_IDField;
        
        private string reuse_FlagField;
        
        private string event_Flow_FlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Access_No {
            get {
                return this.access_NoField;
            }
            set {
                this.access_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BUILDING_NAME {
            get {
                return this.bUILDING_NAMEField;
            }
            set {
                this.bUILDING_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FOA_Submit_date {
            get {
                return this.fOA_Submit_dateField;
            }
            set {
                this.fOA_Submit_dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Mobile_Contact {
            get {
                return this.mobile_ContactField;
            }
            set {
                this.mobile_ContactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OLT_NAME {
            get {
                return this.oLT_NAMEField;
            }
            set {
                this.oLT_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OrderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public NewRegistFOAProductList[] ProductList {
            get {
                return this.productListField;
            }
            set {
                this.productListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RejectReason {
            get {
                return this.rejectReasonField;
            }
            set {
                this.rejectReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public NewRegistFOAServiceList[] ServiceList {
            get {
                return this.serviceListField;
            }
            set {
                this.serviceListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SubcontractorCode {
            get {
                return this.subcontractorCodeField;
            }
            set {
                this.subcontractorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SubcontractorName {
            get {
                return this.subcontractorNameField;
            }
            set {
                this.subcontractorNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SubmitFlag {
            get {
                return this.submitFlagField;
            }
            set {
                this.submitFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Post_Date {
            get {
                return this.post_DateField;
            }
            set {
                this.post_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Address_ID {
            get {
                return this.address_IDField;
            }
            set {
                this.address_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ORG_ID {
            get {
                return this.oRG_IDField;
            }
            set {
                this.oRG_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Reuse_Flag {
            get {
                return this.reuse_FlagField;
            }
            set {
                this.reuse_FlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Event_Flow_Flag {
            get {
                return this.event_Flow_FlagField;
            }
            set {
                this.event_Flow_FlagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WBBEntity.PanelModels.ExWebServiceModels")]
    public partial class NewRegistFOAProductList {
        
        private string companyCodeField;
        
        private string materialCodeField;
        
        private string movementTypeField;
        
        private string plantField;
        
        private string sNPatternField;
        
        private string serialNumberField;
        
        private string storageLocationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MaterialCode {
            get {
                return this.materialCodeField;
            }
            set {
                this.materialCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MovementType {
            get {
                return this.movementTypeField;
            }
            set {
                this.movementTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Plant {
            get {
                return this.plantField;
            }
            set {
                this.plantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SNPattern {
            get {
                return this.sNPatternField;
            }
            set {
                this.sNPatternField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StorageLocation {
            get {
                return this.storageLocationField;
            }
            set {
                this.storageLocationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WBBEntity.PanelModels.ExWebServiceModels")]
    public partial class ProductList {
        
        private string cPE_TypeField;
        
        private string product_CodeField;
        
        private string product_NameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CPE_Type {
            get {
                return this.cPE_TypeField;
            }
            set {
                this.cPE_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Product_Code {
            get {
                return this.product_CodeField;
            }
            set {
                this.product_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Product_Name {
            get {
                return this.product_NameField;
            }
            set {
                this.product_NameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RenewServiceQuery))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WBBEntity.PanelModels.ExWebServiceModels")]
    public partial class RenewService {
        
        private string create_datetimeField;
        
        private string internet_NumberField;
        
        private ProductList[] productListField;
        
        private string send_TypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Create_datetime {
            get {
                return this.create_datetimeField;
            }
            set {
                this.create_datetimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Internet_Number {
            get {
                return this.internet_NumberField;
            }
            set {
                this.internet_NumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ProductList[] ProductList {
            get {
                return this.productListField;
            }
            set {
                this.productListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Send_Type {
            get {
                return this.send_TypeField;
            }
            set {
                this.send_TypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WBBContract.Queries.ExWebServices")]
    public partial class RenewServiceQuery : RenewService {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RenewServiceResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TerminateServiceResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WBBEntity.PanelModels.ExWebServiceModels")]
    public partial class SAPResponse {
        
        private int rETURN_CODEField;
        
        private bool rETURN_CODEFieldSpecified;
        
        private string rETURN_MESSAGEField;
        
        /// <remarks/>
        public int RETURN_CODE {
            get {
                return this.rETURN_CODEField;
            }
            set {
                this.rETURN_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RETURN_CODESpecified {
            get {
                return this.rETURN_CODEFieldSpecified;
            }
            set {
                this.rETURN_CODEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RETURN_MESSAGE {
            get {
                return this.rETURN_MESSAGEField;
            }
            set {
                this.rETURN_MESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WBBEntity.PanelModels.ExWebServiceModels")]
    public partial class RenewServiceResponse : SAPResponse {
        
        private string aSSET_CODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ASSET_CODE {
            get {
                return this.aSSET_CODEField;
            }
            set {
                this.aSSET_CODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WBBEntity.PanelModels.ExWebServiceModels")]
    public partial class TerminateServiceResponse : SAPResponse {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TerminateServiceQuery))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WBBEntity.PanelModels.ExWebServiceModels")]
    public partial class TerminateService {
        
        private string asset_Code_ListField;
        
        private string internet_NumberField;
        
        private string order_StatusField;
        
        private string send_TypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Asset_Code_List {
            get {
                return this.asset_Code_ListField;
            }
            set {
                this.asset_Code_ListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Internet_Number {
            get {
                return this.internet_NumberField;
            }
            set {
                this.internet_NumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Order_Status {
            get {
                return this.order_StatusField;
            }
            set {
                this.order_StatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Send_Type {
            get {
                return this.send_TypeField;
            }
            set {
                this.send_TypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WBBContract.Queries.ExWebServices")]
    public partial class TerminateServiceQuery : TerminateService {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WBBEntity.PanelModels.ExWebServiceModels")]
    public partial class InstallationCostResponse {
        
        private string cOMPANYField;
        
        private string dOCNOField;
        
        private string mESSAGEField;
        
        private string nUMBERField;
        
        private string rEC_TYPEField;
        
        private string rEF_LEGACYField;
        
        private string rUN_GROUPField;
        
        private string yEARField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string COMPANY {
            get {
                return this.cOMPANYField;
            }
            set {
                this.cOMPANYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DOCNO {
            get {
                return this.dOCNOField;
            }
            set {
                this.dOCNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string REC_TYPE {
            get {
                return this.rEC_TYPEField;
            }
            set {
                this.rEC_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string REF_LEGACY {
            get {
                return this.rEF_LEGACYField;
            }
            set {
                this.rEF_LEGACYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RUN_GROUP {
            get {
                return this.rUN_GROUPField;
            }
            set {
                this.rUN_GROUPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string YEAR {
            get {
                return this.yEARField;
            }
            set {
                this.yEARField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstallationCostQuery))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WBBEntity.PanelModels.ExWebServiceModels")]
    public partial class InstallationCost {
        
        private string accountField;
        
        private string amount_in_Document_CurrencyField;
        
        private string currencyField;
        
        private string doc_Header_TextField;
        
        private string document_TypeField;
        
        private string rEC_TYPEField;
        
        private string rUN_GROUPField;
        
        private string rateField;
        
        private string reference_Key_1Field;
        
        private string reference_Key_2Field;
        
        private string reference_Key_3Field;
        
        private string translation_DateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Amount_in_Document_Currency {
            get {
                return this.amount_in_Document_CurrencyField;
            }
            set {
                this.amount_in_Document_CurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Doc_Header_Text {
            get {
                return this.doc_Header_TextField;
            }
            set {
                this.doc_Header_TextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Document_Type {
            get {
                return this.document_TypeField;
            }
            set {
                this.document_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string REC_TYPE {
            get {
                return this.rEC_TYPEField;
            }
            set {
                this.rEC_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RUN_GROUP {
            get {
                return this.rUN_GROUPField;
            }
            set {
                this.rUN_GROUPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Reference_Key_1 {
            get {
                return this.reference_Key_1Field;
            }
            set {
                this.reference_Key_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Reference_Key_2 {
            get {
                return this.reference_Key_2Field;
            }
            set {
                this.reference_Key_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Reference_Key_3 {
            get {
                return this.reference_Key_3Field;
            }
            set {
                this.reference_Key_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Translation_Date {
            get {
                return this.translation_DateField;
            }
            set {
                this.translation_DateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WBBContract.Queries.ExWebServices")]
    public partial class InstallationCostQuery : InstallationCost {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WBBEntity.PanelModels.ExWebServiceModels")]
    public partial class JoinOrderResponse {
        
        private string aSSET_NOField;
        
        private string aSSET_SUBField;
        
        private string dOC_YEARField;
        
        private string eRR_CODEField;
        
        private string mATERIAL_DOCField;
        
        private string mATERIAL_NOField;
        
        private string rEC_TYPEField;
        
        private string rEF_DOC_ITEMField;
        
        private string rEF_DOC_NOField;
        
        private string rUN_GROUPField;
        
        private string sERIAL_NOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ASSET_NO {
            get {
                return this.aSSET_NOField;
            }
            set {
                this.aSSET_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ASSET_SUB {
            get {
                return this.aSSET_SUBField;
            }
            set {
                this.aSSET_SUBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DOC_YEAR {
            get {
                return this.dOC_YEARField;
            }
            set {
                this.dOC_YEARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ERR_CODE {
            get {
                return this.eRR_CODEField;
            }
            set {
                this.eRR_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MATERIAL_DOC {
            get {
                return this.mATERIAL_DOCField;
            }
            set {
                this.mATERIAL_DOCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MATERIAL_NO {
            get {
                return this.mATERIAL_NOField;
            }
            set {
                this.mATERIAL_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string REC_TYPE {
            get {
                return this.rEC_TYPEField;
            }
            set {
                this.rEC_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string REF_DOC_ITEM {
            get {
                return this.rEF_DOC_ITEMField;
            }
            set {
                this.rEF_DOC_ITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string REF_DOC_NO {
            get {
                return this.rEF_DOC_NOField;
            }
            set {
                this.rEF_DOC_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RUN_GROUP {
            get {
                return this.rUN_GROUPField;
            }
            set {
                this.rUN_GROUPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SERIAL_NO {
            get {
                return this.sERIAL_NOField;
            }
            set {
                this.sERIAL_NOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JoinOrderQuery))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WBBEntity.PanelModels.ExWebServiceModels")]
    public partial class JoinOrder {
        
        private string dOC_HEADER_TXTField;
        
        private string gL_ACCTField;
        
        private string iTEM_TEXTField;
        
        private string mATERIAL_NOField;
        
        private string mOVEMENT_TYPEField;
        
        private string pLANT_FROMField;
        
        private string qUANTITYField;
        
        private string rEC_TYPEField;
        
        private string rEF_DOC_ITEMField;
        
        private string rEF_DOC_NOField;
        
        private string rUN_GROUPField;
        
        private string sERIAL_NOField;
        
        private string sLOC_FROMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DOC_HEADER_TXT {
            get {
                return this.dOC_HEADER_TXTField;
            }
            set {
                this.dOC_HEADER_TXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GL_ACCT {
            get {
                return this.gL_ACCTField;
            }
            set {
                this.gL_ACCTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ITEM_TEXT {
            get {
                return this.iTEM_TEXTField;
            }
            set {
                this.iTEM_TEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MATERIAL_NO {
            get {
                return this.mATERIAL_NOField;
            }
            set {
                this.mATERIAL_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MOVEMENT_TYPE {
            get {
                return this.mOVEMENT_TYPEField;
            }
            set {
                this.mOVEMENT_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PLANT_FROM {
            get {
                return this.pLANT_FROMField;
            }
            set {
                this.pLANT_FROMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string QUANTITY {
            get {
                return this.qUANTITYField;
            }
            set {
                this.qUANTITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string REC_TYPE {
            get {
                return this.rEC_TYPEField;
            }
            set {
                this.rEC_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string REF_DOC_ITEM {
            get {
                return this.rEF_DOC_ITEMField;
            }
            set {
                this.rEF_DOC_ITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string REF_DOC_NO {
            get {
                return this.rEF_DOC_NOField;
            }
            set {
                this.rEF_DOC_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RUN_GROUP {
            get {
                return this.rUN_GROUPField;
            }
            set {
                this.rUN_GROUPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SERIAL_NO {
            get {
                return this.sERIAL_NOField;
            }
            set {
                this.sERIAL_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SLOC_FROM {
            get {
                return this.sLOC_FROMField;
            }
            set {
                this.sLOC_FROMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WBBContract.Queries.ExWebServices")]
    public partial class JoinOrderQuery : JoinOrder {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WBBEntity.PanelModels.ExWebServiceModels")]
    public partial class NewRegisterResponse {
        
        private string cOMPANYField;
        
        private string mAIN_ASSETField;
        
        private string mESSAGEField;
        
        private string nUMBERField;
        
        private string rEC_TYPEField;
        
        private string rEFERENCEField;
        
        private string rUN_GROUPField;
        
        private string sUBNUMBERField;
        
        private string tYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string COMPANY {
            get {
                return this.cOMPANYField;
            }
            set {
                this.cOMPANYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MAIN_ASSET {
            get {
                return this.mAIN_ASSETField;
            }
            set {
                this.mAIN_ASSETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string REC_TYPE {
            get {
                return this.rEC_TYPEField;
            }
            set {
                this.rEC_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string REFERENCE {
            get {
                return this.rEFERENCEField;
            }
            set {
                this.rEFERENCEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RUN_GROUP {
            get {
                return this.rUN_GROUPField;
            }
            set {
                this.rUN_GROUPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SUBNUMBER {
            get {
                return this.sUBNUMBERField;
            }
            set {
                this.sUBNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewRegisterQuery))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WBBEntity.PanelModels.ExWebServiceModels")]
    public partial class Register {
        
        private string aSSET_CLASSField;
        
        private string aSSET_DESC1Field;
        
        private string aSSET_DESC2Field;
        
        private string cOM_CODEField;
        
        private string cOSTCENTERField;
        
        private string dOC_DATEField;
        
        private string eVA4Field;
        
        private string eVA5Field;
        
        private string iNV_NOField;
        
        private string mAIN_ASSETField;
        
        private string pOST_DATEField;
        
        private string rEC_TYPEField;
        
        private string rUN_GROUPField;
        
        private string sUBNUMBERField;
        
        private string xREF1_HDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ASSET_CLASS {
            get {
                return this.aSSET_CLASSField;
            }
            set {
                this.aSSET_CLASSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ASSET_DESC1 {
            get {
                return this.aSSET_DESC1Field;
            }
            set {
                this.aSSET_DESC1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ASSET_DESC2 {
            get {
                return this.aSSET_DESC2Field;
            }
            set {
                this.aSSET_DESC2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string COM_CODE {
            get {
                return this.cOM_CODEField;
            }
            set {
                this.cOM_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string COSTCENTER {
            get {
                return this.cOSTCENTERField;
            }
            set {
                this.cOSTCENTERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DOC_DATE {
            get {
                return this.dOC_DATEField;
            }
            set {
                this.dOC_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EVA4 {
            get {
                return this.eVA4Field;
            }
            set {
                this.eVA4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EVA5 {
            get {
                return this.eVA5Field;
            }
            set {
                this.eVA5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string INV_NO {
            get {
                return this.iNV_NOField;
            }
            set {
                this.iNV_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MAIN_ASSET {
            get {
                return this.mAIN_ASSETField;
            }
            set {
                this.mAIN_ASSETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string POST_DATE {
            get {
                return this.pOST_DATEField;
            }
            set {
                this.pOST_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string REC_TYPE {
            get {
                return this.rEC_TYPEField;
            }
            set {
                this.rEC_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RUN_GROUP {
            get {
                return this.rUN_GROUPField;
            }
            set {
                this.rUN_GROUPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SUBNUMBER {
            get {
                return this.sUBNUMBERField;
            }
            set {
                this.sUBNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string XREF1_HD {
            get {
                return this.xREF1_HDField;
            }
            set {
                this.xREF1_HDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WBBContract.Queries.ExWebServices")]
    public partial class NewRegisterQuery : Register {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WBBEntity.PanelModels.ExWebServiceModels")]
    public partial class NewRegistForSubmitFOAResponse {
        
        private string errorReasonField;
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errorReason {
            get {
                return this.errorReasonField;
            }
            set {
                this.errorReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WBBEntity.PanelModels.ExWebServiceModels")]
    public partial class NewRegistFOAServiceList {
        
        private string serviceNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void NewRegistForSubmitFOACompletedEventHandler(object sender, NewRegistForSubmitFOACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewRegistForSubmitFOACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NewRegistForSubmitFOACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NewRegistForSubmitFOAResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NewRegistForSubmitFOAResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void NewRegistOrderCompletedEventHandler(object sender, NewRegistOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewRegistOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NewRegistOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NewRegisterResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NewRegisterResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void JoinOrderCompletedEventHandler(object sender, JoinOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JoinOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal JoinOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public JoinOrderResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((JoinOrderResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void InstallationCostCompletedEventHandler(object sender, InstallationCostCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InstallationCostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InstallationCostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InstallationCostResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InstallationCostResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void TerminateServiceCompletedEventHandler(object sender, TerminateServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TerminateServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TerminateServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TerminateServiceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TerminateServiceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void RenewServiceCompletedEventHandler(object sender, RenewServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RenewServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RenewServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RenewServiceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RenewServiceResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591