//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBBBusinessLayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dblogintest.ais.co.th/wsAuthenDB/webDBconfigService.asmx")]
        public string WBBBusinessLayer_AuthenDBServices_WebDBConfigService {
            get {
                return ((string)(this["WBBBusinessLayer_AuthenDBServices_WebDBConfigService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.240.1.214:2521/web/services/subscriberstatewebservice.asmx")]
        public string WBBBusinessLayer_SubscriberStateWebService_SubscriberStateWebService {
            get {
                return ((string)(this["WBBBusinessLayer_SubscriberStateWebService_SubscriberStateWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.240.141.222:8080/GSSO-SSO/GssoSsoWeb")]
        public string WBBBusinessLayer_GssoSsoWebService_GssoSsoWebService {
            get {
                return ((string)(this["WBBBusinessLayer_GssoSsoWebService_GssoSsoWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.13.181.71:8280/CampaignWS/services/CampaignDataService.CampaignDataServ" +
            "iceHttpSoap11Endpoint/")]
        public string WBBBusinessLayer_CampaignDataServices_CampaignDataService {
            get {
                return ((string)(this["WBBBusinessLayer_CampaignDataServices_CampaignDataService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.252.54.24:7111/FBB/Proxy_Services/A_GetCCCustInfo")]
        public string WBBBusinessLayer_WebReference_FBB_BindingQSService {
            get {
                return ((string)(this["WBBBusinessLayer_WebReference_FBB_BindingQSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pidev:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=BS_FBS" +
            "S&receiverParty=&receiverService=&interface=SI_Z_FIAM_FBSS_FIXEDASSET&interfaceN" +
            "amespace=urn%3Aais.co.th%3AFI%3AFBSS%3AZ_FIAM_FBSS_FIXEDASSET")]
        public string WBBBusinessLayer_SAP_FixedAssetService {
            get {
                return ((string)(this["WBBBusinessLayer_SAP_FixedAssetService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.252.64.129:8803/SFFWebService/SFFService")]
        public string WBBBusinessLayer_SFFServices_SFFServiceService {
            get {
                return ((string)(this["WBBBusinessLayer_SFFServices_SFFServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dev-ldapws.intra.ais/AisEmployee/AisEmployeService.asmx")]
        public string WBBBusinessLayer_AisEmployeServices_AisEmployeService {
            get {
                return ((string)(this["WBBBusinessLayer_AisEmployeServices_AisEmployeService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.197.51.164/services/smsSurveyFOA/index.php")]
        public string WBBBusinessLayer_SmsSurveyFOAWebService_smsSurveyFOA {
            get {
                return ((string)(this["WBBBusinessLayer_SmsSurveyFOAWebService_smsSurveyFOA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://fixedbbws.ais.co.th/ExWebServices/FBBSAPOnline.svc")]
        public string WBBBusinessLayer_FBBSAPOnline1_FBBSAPOnline {
            get {
                return ((string)(this["WBBBusinessLayer_FBBSAPOnline1_FBBSAPOnline"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pidev:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=BS_FBS" +
            "S&receiverParty=&receiverService=&interface=SI_Z_FIAM_FBSS_REVALUATION_ASSET&int" +
            "erfaceNamespace=urn%3Aais.co.th%3AFI%3AFBSS%3AZ_FIAM_FBSS_REVALUATION_ASSET")]
        public string WBBBusinessLayer_FBBSAPOnlineRevalue_SI_Z_FIAM_FBSS_REVALUATION_ASSETService {
            get {
                return ((string)(this["WBBBusinessLayer_FBBSAPOnlineRevalue_SI_Z_FIAM_FBSS_REVALUATION_ASSETService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pidev:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=BS_FBS" +
            "S&receiverParty=&receiverService=&interface=SI_Z_MMIM_FBSS_TRANS_POST&interfaceN" +
            "amespace=urn%3Aais.co.th%3AMM%3AFBSS%3AZ_MMIM_FBSS_TRANS_POST")]
        public string WBBBusinessLayer_FBBSAPOnlineMA_SI_Z_MMIM_FBSS_TRANS_POSTService {
            get {
                return ((string)(this["WBBBusinessLayer_FBBSAPOnlineMA_SI_Z_MMIM_FBSS_TRANS_POSTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.138.39.106:8180/airnet-service/SBNWebService")]
        public string WBBBusinessLayer_SBNNewWebService_SBNWebServiceService {
            get {
                return ((string)(this["WBBBusinessLayer_SBNNewWebService_SBNWebServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://test-omws.ais.co.th/omws/WS_OM_OMService.svc")]
        public string WBBBusinessLayer_OMWService_WS_OM_OMService {
            get {
                return ((string)(this["WBBBusinessLayer_OMWService_WS_OM_OMService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.252.162/eai/start.swe?SWEExtSource=WebService&SWEExtCmd=Execute&Use" +
            "rname=UserName&Password=Password")]
        public string WBBBusinessLayer_Siebel_CreateTroubleTicketService_AIS_spcCreate_spcTrouble_spcTicket {
            get {
                return ((string)(this["WBBBusinessLayer_Siebel_CreateTroubleTicketService_AIS_spcCreate_spcTrouble_spcTi" +
                    "cket"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.252.162/eai/start.swe?SWEExtSource=WebService&SWEExtCmd=Execute&Use" +
            "rname=Username&Password=Password")]
        public string WBBBusinessLayer_SiebelGenActivity_AIS_spcIM_spcCommon_spcCreate_spcActivity {
            get {
                return ((string)(this["WBBBusinessLayer_SiebelGenActivity_AIS_spcIM_spcCommon_spcCreate_spcActivity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.252.162/eai/start.swe?SWEExtSource=WebService&SWEExtCmd=Execute&Use" +
            "rname=Username&Password=Password")]
        public string WBBBusinessLayer_SiebelService_AIS_spcDRM_spcChannel_spcInfo {
            get {
                return ((string)(this["WBBBusinessLayer_SiebelService_AIS_spcDRM_spcChannel_spcInfo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.138.32.21:8080/prweb/PRSOAPServlet/SOAP/AISNIMIntFBBIntegration/Service" +
            "s")]
        public string WBBBusinessLayer_IMService_ServicesService {
            get {
                return ((string)(this["WBBBusinessLayer_IMService_ServicesService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pidev:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=BS_FBS" +
            "S&receiverParty=&receiverService=&interface=SI_Z_MMIM_FBSS_TRANS_POST&interfaceN" +
            "amespace=urn%3Aais.co.th%3AMM%3AFBSS%3AZ_MMIM_FBSS_TRANS_POST")]
        public string WBBBusinessLayer_FBBSAPOnlineMA2_SI_Z_MMIM_FBSS_TRANS_POSTService {
            get {
                return ((string)(this["WBBBusinessLayer_FBBSAPOnlineMA2_SI_Z_MMIM_FBSS_TRANS_POSTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dev-airnetregws.ais.co.th:8543/airnet-service/AIRInterfaceWorkflowService" +
            "?wsdl")]
        public string One2NetBusinessLayer_SBNNewWebService_SBNWebServiceService {
            get {
                return ((string)(this["One2NetBusinessLayer_SBNNewWebService_SBNWebServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.104.140.72/WTTxResourceManagement/services/wttxinventory")]
        public string WBBBusinessLayer_WTTxInventory_WTTxInventoryService {
            get {
                return ((string)(this["WBBBusinessLayer_WTTxInventory_WTTxInventoryService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.252.54.75:8101/e-topup_Project/Proxy_Services/A_ConfPMPay")]
        public string WBBBusinessLayer_BindingQSServices_tuxsalt_BindingQSService {
            get {
                return ((string)(this["WBBBusinessLayer_BindingQSServices_tuxsalt_BindingQSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.252.54.75:8101/eBILL_Projects/Proxy_Services/D_LstPMETaxRcpt")]
        public string WBBBusinessLayer_D_LstPMETaxRcptServices_eBill_webservices_BindingQSService1 {
            get {
                return ((string)(this["WBBBusinessLayer_D_LstPMETaxRcptServices_eBill_webservices_BindingQSService1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.13.181.46:8701/airnet-service/SBNWebService")]
        public string WBBBusinessLayer_SBNWebService_SBNWebServiceService {
            get {
                return ((string)(this["WBBBusinessLayer_SBNWebService_SBNWebServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.138.26.230:7105/axis2/services/OrderService/")]
        public string WBBBusinessLayer_FBSSOrderServices_OrderService {
            get {
                return ((string)(this["WBBBusinessLayer_FBSSOrderServices_OrderService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.138.26.228:7101/axis2/services/TTComplainSheet/")]
        public string WBBBusinessLayer_TTComplainSheet_TTComplainSheet {
            get {
                return ((string)(this["WBBBusinessLayer_TTComplainSheet_TTComplainSheet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dev-airnetregws.ais.co.th:8543/airnet-service/AIRInterfaceWorkflowService" +
            "")]
        public string WBBBusinessLayer_SBNV2WebService_AIRInterfaceWorkflowServiceService {
            get {
                return ((string)(this["WBBBusinessLayer_SBNV2WebService_AIRInterfaceWorkflowServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dev-ldapws.intra.ais/AisEmployee/AisEmployeService.asmx?wsdl")]
        public string WBBBusinessLayer_AuthenLDAPServices_CorporateService {
            get {
                return ((string)(this["WBBBusinessLayer_AuthenLDAPServices_CorporateService"]));
            }
        }
    }
}
