//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WBBBusinessLayer.SubscriberWebService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SubscriberStateWebServiceSoap", Namespace="http://vsmp.ais.co.th/webservices/subscriber/")]
    public partial class SubscriberStateWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ModifySubscriberStateOnlineOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModifySubscriberStateOfflineOperationCompleted;
        
        private System.Threading.SendOrPostCallback InquiryVASSubscriberOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SubscriberStateWebService() {
            this.Url = global::WBBBusinessLayer.Properties.Settings.Default.WBBBusinessLayer_SubscriberStateWebService_SubscriberStateWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ModifySubscriberStateOnlineCompletedEventHandler ModifySubscriberStateOnlineCompleted;
        
        /// <remarks/>
        public event ModifySubscriberStateOfflineCompletedEventHandler ModifySubscriberStateOfflineCompleted;
        
        /// <remarks/>
        public event InquiryVASSubscriberCompletedEventHandler InquiryVASSubscriberCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vsmp.ais.co.th/webservices/subscriber/ModifySubscriberStateOnline", RequestNamespace="http://vsmp.ais.co.th/webservices/subscriber/", ResponseNamespace="http://vsmp.ais.co.th/webservices/subscriber/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SubscriberResponse ModifySubscriberStateOnline(string Username, string OrderRef, string OrderDesc, string Msisdn, string State) {
            object[] results = this.Invoke("ModifySubscriberStateOnline", new object[] {
                        Username,
                        OrderRef,
                        OrderDesc,
                        Msisdn,
                        State});
            return ((SubscriberResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ModifySubscriberStateOnlineAsync(string Username, string OrderRef, string OrderDesc, string Msisdn, string State) {
            this.ModifySubscriberStateOnlineAsync(Username, OrderRef, OrderDesc, Msisdn, State, null);
        }
        
        /// <remarks/>
        public void ModifySubscriberStateOnlineAsync(string Username, string OrderRef, string OrderDesc, string Msisdn, string State, object userState) {
            if ((this.ModifySubscriberStateOnlineOperationCompleted == null)) {
                this.ModifySubscriberStateOnlineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifySubscriberStateOnlineOperationCompleted);
            }
            this.InvokeAsync("ModifySubscriberStateOnline", new object[] {
                        Username,
                        OrderRef,
                        OrderDesc,
                        Msisdn,
                        State}, this.ModifySubscriberStateOnlineOperationCompleted, userState);
        }
        
        private void OnModifySubscriberStateOnlineOperationCompleted(object arg) {
            if ((this.ModifySubscriberStateOnlineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModifySubscriberStateOnlineCompleted(this, new ModifySubscriberStateOnlineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vsmp.ais.co.th/webservices/subscriber/ModifySubscriberStateOffline", RequestNamespace="http://vsmp.ais.co.th/webservices/subscriber/", ResponseNamespace="http://vsmp.ais.co.th/webservices/subscriber/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SubscriberResponse ModifySubscriberStateOffline(string Username, string OrderRef, string OrderDesc, string Msisdn, string State) {
            object[] results = this.Invoke("ModifySubscriberStateOffline", new object[] {
                        Username,
                        OrderRef,
                        OrderDesc,
                        Msisdn,
                        State});
            return ((SubscriberResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ModifySubscriberStateOfflineAsync(string Username, string OrderRef, string OrderDesc, string Msisdn, string State) {
            this.ModifySubscriberStateOfflineAsync(Username, OrderRef, OrderDesc, Msisdn, State, null);
        }
        
        /// <remarks/>
        public void ModifySubscriberStateOfflineAsync(string Username, string OrderRef, string OrderDesc, string Msisdn, string State, object userState) {
            if ((this.ModifySubscriberStateOfflineOperationCompleted == null)) {
                this.ModifySubscriberStateOfflineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifySubscriberStateOfflineOperationCompleted);
            }
            this.InvokeAsync("ModifySubscriberStateOffline", new object[] {
                        Username,
                        OrderRef,
                        OrderDesc,
                        Msisdn,
                        State}, this.ModifySubscriberStateOfflineOperationCompleted, userState);
        }
        
        private void OnModifySubscriberStateOfflineOperationCompleted(object arg) {
            if ((this.ModifySubscriberStateOfflineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModifySubscriberStateOfflineCompleted(this, new ModifySubscriberStateOfflineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vsmp.ais.co.th/webservices/subscriber/InquiryVASSubscriber", RequestNamespace="http://vsmp.ais.co.th/webservices/subscriber/", ResponseNamespace="http://vsmp.ais.co.th/webservices/subscriber/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InquiryVASSubscriberResponce InquiryVASSubscriber(string Username, string OrderRef, string OrderDesc, string Msisdn, string opt1, string opt2) {
            object[] results = this.Invoke("InquiryVASSubscriber", new object[] {
                        Username,
                        OrderRef,
                        OrderDesc,
                        Msisdn,
                        opt1,
                        opt2});
            return ((InquiryVASSubscriberResponce)(results[0]));
        }
        
        /// <remarks/>
        public void InquiryVASSubscriberAsync(string Username, string OrderRef, string OrderDesc, string Msisdn, string opt1, string opt2) {
            this.InquiryVASSubscriberAsync(Username, OrderRef, OrderDesc, Msisdn, opt1, opt2, null);
        }
        
        /// <remarks/>
        public void InquiryVASSubscriberAsync(string Username, string OrderRef, string OrderDesc, string Msisdn, string opt1, string opt2, object userState) {
            if ((this.InquiryVASSubscriberOperationCompleted == null)) {
                this.InquiryVASSubscriberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInquiryVASSubscriberOperationCompleted);
            }
            this.InvokeAsync("InquiryVASSubscriber", new object[] {
                        Username,
                        OrderRef,
                        OrderDesc,
                        Msisdn,
                        opt1,
                        opt2}, this.InquiryVASSubscriberOperationCompleted, userState);
        }
        
        private void OnInquiryVASSubscriberOperationCompleted(object arg) {
            if ((this.InquiryVASSubscriberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InquiryVASSubscriberCompleted(this, new InquiryVASSubscriberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vsmp.ais.co.th/webservices/subscriber/")]
    public partial class SubscriberResponse {
        
        private Status operationStatusField;
        
        private SubscriberInfo subscriberField;
        
        /// <remarks/>
        public Status OperationStatus {
            get {
                return this.operationStatusField;
            }
            set {
                this.operationStatusField = value;
            }
        }
        
        /// <remarks/>
        public SubscriberInfo Subscriber {
            get {
                return this.subscriberField;
            }
            set {
                this.subscriberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vsmp.ais.co.th/webservices/subscriber/")]
    public partial class Status {
        
        private bool isSuccessField;
        
        private string codeField;
        
        private string descriptionField;
        
        private string transactionIDField;
        
        private string orderRefField;
        
        /// <remarks/>
        public bool IsSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OrderRef {
            get {
                return this.orderRefField;
            }
            set {
                this.orderRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vsmp.ais.co.th/webservices/subscriber/")]
    public partial class SubscriberVASInfo {
        
        private string msisdnField;
        
        private string machineIDField;
        
        private string sttField;
        
        private string customerIdField;
        
        private string stateField;
        
        private string languageField;
        
        private string hacktimeField;
        
        private string cosField;
        
        private string mProductIDField;
        
        private string mobileLocationField;
        
        private string servicePackageIDField;
        
        private string sCPIDField;
        
        private string cBPIDField;
        
        private string gprsTBCFField;
        
        private string altAccPrefixFField;
        
        private string altAccPrefixCosField;
        
        private string altAccToggleStateField;
        
        private string altAccToggleCosField;
        
        private string toggleFField;
        
        private string nwtField;
        
        private string chmField;
        
        private string spNameField;
        
        private string brandIdField;
        
        private string cfAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string machineID {
            get {
                return this.machineIDField;
            }
            set {
                this.machineIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string stt {
            get {
                return this.sttField;
            }
            set {
                this.sttField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string hacktime {
            get {
                return this.hacktimeField;
            }
            set {
                this.hacktimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cos {
            get {
                return this.cosField;
            }
            set {
                this.cosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MProductID {
            get {
                return this.mProductIDField;
            }
            set {
                this.mProductIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mobileLocation {
            get {
                return this.mobileLocationField;
            }
            set {
                this.mobileLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServicePackageID {
            get {
                return this.servicePackageIDField;
            }
            set {
                this.servicePackageIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SCPID {
            get {
                return this.sCPIDField;
            }
            set {
                this.sCPIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CBPID {
            get {
                return this.cBPIDField;
            }
            set {
                this.cBPIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string gprsTBCF {
            get {
                return this.gprsTBCFField;
            }
            set {
                this.gprsTBCFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string altAccPrefixF {
            get {
                return this.altAccPrefixFField;
            }
            set {
                this.altAccPrefixFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string altAccPrefixCos {
            get {
                return this.altAccPrefixCosField;
            }
            set {
                this.altAccPrefixCosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string altAccToggleState {
            get {
                return this.altAccToggleStateField;
            }
            set {
                this.altAccToggleStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string altAccToggleCos {
            get {
                return this.altAccToggleCosField;
            }
            set {
                this.altAccToggleCosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string toggleF {
            get {
                return this.toggleFField;
            }
            set {
                this.toggleFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nwt {
            get {
                return this.nwtField;
            }
            set {
                this.nwtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string chm {
            get {
                return this.chmField;
            }
            set {
                this.chmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string spName {
            get {
                return this.spNameField;
            }
            set {
                this.spNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string brandId {
            get {
                return this.brandIdField;
            }
            set {
                this.brandIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cfAddress {
            get {
                return this.cfAddressField;
            }
            set {
                this.cfAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vsmp.ais.co.th/webservices/subscriber/")]
    public partial class InquiryVASSubscriberResponce {
        
        private Status operationStatusField;
        
        private SubscriberVASInfo subscriberField;
        
        /// <remarks/>
        public Status OperationStatus {
            get {
                return this.operationStatusField;
            }
            set {
                this.operationStatusField = value;
            }
        }
        
        /// <remarks/>
        public SubscriberVASInfo Subscriber {
            get {
                return this.subscriberField;
            }
            set {
                this.subscriberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vsmp.ais.co.th/webservices/subscriber/")]
    public partial class ImsiInfo {
        
        private string imsiField;
        
        private string imsiS1Field;
        
        private string msisdnS1Field;
        
        private string imsiS2Field;
        
        private string msisdnS2Field;
        
        private string imsiS3Field;
        
        private string msisdnS3Field;
        
        private string imsiS4Field;
        
        private string msisdnS4Field;
        
        private string imsiXField;
        
        private string msisdnImsiXField;
        
        private string imsiFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string imsi {
            get {
                return this.imsiField;
            }
            set {
                this.imsiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string imsiS1 {
            get {
                return this.imsiS1Field;
            }
            set {
                this.imsiS1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string msisdnS1 {
            get {
                return this.msisdnS1Field;
            }
            set {
                this.msisdnS1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string imsiS2 {
            get {
                return this.imsiS2Field;
            }
            set {
                this.imsiS2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string msisdnS2 {
            get {
                return this.msisdnS2Field;
            }
            set {
                this.msisdnS2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string imsiS3 {
            get {
                return this.imsiS3Field;
            }
            set {
                this.imsiS3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string msisdnS3 {
            get {
                return this.msisdnS3Field;
            }
            set {
                this.msisdnS3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string imsiS4 {
            get {
                return this.imsiS4Field;
            }
            set {
                this.imsiS4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string msisdnS4 {
            get {
                return this.msisdnS4Field;
            }
            set {
                this.msisdnS4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string imsiX {
            get {
                return this.imsiXField;
            }
            set {
                this.imsiXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string msisdnImsiX {
            get {
                return this.msisdnImsiXField;
            }
            set {
                this.msisdnImsiXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string imsiFlag {
            get {
                return this.imsiFlagField;
            }
            set {
                this.imsiFlagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vsmp.ais.co.th/webservices/subscriber/")]
    public partial class SubscriberInfo {
        
        private string msisdnField;
        
        private string customerIDField;
        
        private string cosField;
        
        private System.DateTime timeField;
        
        private string langField;
        
        private string modelField;
        
        private string stateField;
        
        private string vscpStateField;
        
        private string servicePackageIdField;
        
        private string hackField;
        
        private string gtcfField;
        
        private string scpIdField;
        
        private string cbpIdField;
        
        private string bsoField;
        
        private int numImsiField;
        
        private string prepaidFlagField;
        
        private string virtualFlagField;
        
        private string altPrefixFlagField;
        
        private string altPrefixCosField;
        
        private string serviceLocationField;
        
        private bool hasOneTimePasswordField;
        
        private bool hasPasswordField;
        
        private string toggleFField;
        
        private string toggleStateField;
        
        private string toggleCosField;
        
        private string cosEffectiveDateField;
        
        private string cosEffectiveValueField;
        
        private string gtcfEffectiveDateField;
        
        private string gtcfEffectiveValueField;
        
        private string firstActDateField;
        
        private ImsiInfo imsiArrayField;
        
        private string spNameField;
        
        private string brandNameField;
        
        private string dateLastModField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cos {
            get {
                return this.cosField;
            }
            set {
                this.cosField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VscpState {
            get {
                return this.vscpStateField;
            }
            set {
                this.vscpStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServicePackageId {
            get {
                return this.servicePackageIdField;
            }
            set {
                this.servicePackageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Hack {
            get {
                return this.hackField;
            }
            set {
                this.hackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Gtcf {
            get {
                return this.gtcfField;
            }
            set {
                this.gtcfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ScpId {
            get {
                return this.scpIdField;
            }
            set {
                this.scpIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CbpId {
            get {
                return this.cbpIdField;
            }
            set {
                this.cbpIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Bso {
            get {
                return this.bsoField;
            }
            set {
                this.bsoField = value;
            }
        }
        
        /// <remarks/>
        public int NumImsi {
            get {
                return this.numImsiField;
            }
            set {
                this.numImsiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PrepaidFlag {
            get {
                return this.prepaidFlagField;
            }
            set {
                this.prepaidFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VirtualFlag {
            get {
                return this.virtualFlagField;
            }
            set {
                this.virtualFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AltPrefixFlag {
            get {
                return this.altPrefixFlagField;
            }
            set {
                this.altPrefixFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AltPrefixCos {
            get {
                return this.altPrefixCosField;
            }
            set {
                this.altPrefixCosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServiceLocation {
            get {
                return this.serviceLocationField;
            }
            set {
                this.serviceLocationField = value;
            }
        }
        
        /// <remarks/>
        public bool HasOneTimePassword {
            get {
                return this.hasOneTimePasswordField;
            }
            set {
                this.hasOneTimePasswordField = value;
            }
        }
        
        /// <remarks/>
        public bool HasPassword {
            get {
                return this.hasPasswordField;
            }
            set {
                this.hasPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ToggleF {
            get {
                return this.toggleFField;
            }
            set {
                this.toggleFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ToggleState {
            get {
                return this.toggleStateField;
            }
            set {
                this.toggleStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ToggleCos {
            get {
                return this.toggleCosField;
            }
            set {
                this.toggleCosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CosEffectiveDate {
            get {
                return this.cosEffectiveDateField;
            }
            set {
                this.cosEffectiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CosEffectiveValue {
            get {
                return this.cosEffectiveValueField;
            }
            set {
                this.cosEffectiveValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GtcfEffectiveDate {
            get {
                return this.gtcfEffectiveDateField;
            }
            set {
                this.gtcfEffectiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GtcfEffectiveValue {
            get {
                return this.gtcfEffectiveValueField;
            }
            set {
                this.gtcfEffectiveValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FirstActDate {
            get {
                return this.firstActDateField;
            }
            set {
                this.firstActDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ImsiInfo imsiArray {
            get {
                return this.imsiArrayField;
            }
            set {
                this.imsiArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string spName {
            get {
                return this.spNameField;
            }
            set {
                this.spNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string brandName {
            get {
                return this.brandNameField;
            }
            set {
                this.brandNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dateLastMod {
            get {
                return this.dateLastModField;
            }
            set {
                this.dateLastModField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ModifySubscriberStateOnlineCompletedEventHandler(object sender, ModifySubscriberStateOnlineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModifySubscriberStateOnlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModifySubscriberStateOnlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SubscriberResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SubscriberResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ModifySubscriberStateOfflineCompletedEventHandler(object sender, ModifySubscriberStateOfflineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModifySubscriberStateOfflineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModifySubscriberStateOfflineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SubscriberResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SubscriberResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void InquiryVASSubscriberCompletedEventHandler(object sender, InquiryVASSubscriberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InquiryVASSubscriberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InquiryVASSubscriberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InquiryVASSubscriberResponce Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InquiryVASSubscriberResponce)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591