//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WBBBusinessLayer.GssoSsoWebService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GssoSsoWebPortBinding", Namespace="http://ws.sso.gsso/")]
    public partial class GssoSsoWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback confirmOneTimePWOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendOneTimePWOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GssoSsoWebService() {
            this.Url = global::WBBBusinessLayer.Properties.Settings.Default.WBBBusinessLayer_GssoSsoWebService_GssoSsoWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event confirmOneTimePWCompletedEventHandler confirmOneTimePWCompleted;
        
        /// <remarks/>
        public event sendOneTimePWCompletedEventHandler sendOneTimePWCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.sso.gsso/", ResponseNamespace="http://ws.sso.gsso/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public gssoSsoResponse confirmOneTimePW([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string msisdn, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string transactionID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string service) {
            object[] results = this.Invoke("confirmOneTimePW", new object[] {
                        msisdn,
                        pwd,
                        transactionID,
                        service});
            return ((gssoSsoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void confirmOneTimePWAsync(string msisdn, string pwd, string transactionID, string service) {
            this.confirmOneTimePWAsync(msisdn, pwd, transactionID, service, null);
        }
        
        /// <remarks/>
        public void confirmOneTimePWAsync(string msisdn, string pwd, string transactionID, string service, object userState) {
            if ((this.confirmOneTimePWOperationCompleted == null)) {
                this.confirmOneTimePWOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconfirmOneTimePWOperationCompleted);
            }
            this.InvokeAsync("confirmOneTimePW", new object[] {
                        msisdn,
                        pwd,
                        transactionID,
                        service}, this.confirmOneTimePWOperationCompleted, userState);
        }
        
        private void OnconfirmOneTimePWOperationCompleted(object arg) {
            if ((this.confirmOneTimePWCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.confirmOneTimePWCompleted(this, new confirmOneTimePWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.sso.gsso/", ResponseNamespace="http://ws.sso.gsso/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public gssoSsoResponse sendOneTimePW([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string msisdn, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string emailAddr, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string otpChannel, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string service, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string accountType, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int addTimeoutMins, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool waitDR, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool waitDRSpecified, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int otpDigit) {
            object[] results = this.Invoke("sendOneTimePW", new object[] {
                        msisdn,
                        emailAddr,
                        otpChannel,
                        service,
                        accountType,
                        addTimeoutMins,
                        waitDR,
                        waitDRSpecified,
                        otpDigit});
            return ((gssoSsoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void sendOneTimePWAsync(string msisdn, string emailAddr, string otpChannel, string service, string accountType, int addTimeoutMins, bool waitDR, bool waitDRSpecified, int otpDigit) {
            this.sendOneTimePWAsync(msisdn, emailAddr, otpChannel, service, accountType, addTimeoutMins, waitDR, waitDRSpecified, otpDigit, null);
        }
        
        /// <remarks/>
        public void sendOneTimePWAsync(string msisdn, string emailAddr, string otpChannel, string service, string accountType, int addTimeoutMins, bool waitDR, bool waitDRSpecified, int otpDigit, object userState) {
            if ((this.sendOneTimePWOperationCompleted == null)) {
                this.sendOneTimePWOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendOneTimePWOperationCompleted);
            }
            this.InvokeAsync("sendOneTimePW", new object[] {
                        msisdn,
                        emailAddr,
                        otpChannel,
                        service,
                        accountType,
                        addTimeoutMins,
                        waitDR,
                        waitDRSpecified,
                        otpDigit}, this.sendOneTimePWOperationCompleted, userState);
        }
        
        private void OnsendOneTimePWOperationCompleted(object arg) {
            if ((this.sendOneTimePWCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendOneTimePWCompleted(this, new sendOneTimePWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sso.gsso/")]
    public partial class gssoSsoResponse {
        
        private string codeField;
        
        private string descriptionField;
        
        private bool isSuccessField;
        
        private string operNameField;
        
        private string orderRefField;
        
        private string pwdField;
        
        private string transactionIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string operName {
            get {
                return this.operNameField;
            }
            set {
                this.operNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderRef {
            get {
                return this.orderRefField;
            }
            set {
                this.orderRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pwd {
            get {
                return this.pwdField;
            }
            set {
                this.pwdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void confirmOneTimePWCompletedEventHandler(object sender, confirmOneTimePWCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class confirmOneTimePWCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal confirmOneTimePWCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public gssoSsoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((gssoSsoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void sendOneTimePWCompletedEventHandler(object sender, sendOneTimePWCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendOneTimePWCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendOneTimePWCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public gssoSsoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((gssoSsoResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591