<?xml version="1.0" encoding="UTF-8"?><definitions
 xmlns="http://schemas.xmlsoap.org/wsdl/"
 xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
 targetNamespace="http://siebel.com/asi/"
 xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:tns="http://siebel.com/asi/"
><types
></types
><message
 name="AISDRMChannelInfo_Input"
><part
 name="inParam5"
 type="xsd:string"
></part
><part
 name="inParam4"
 type="xsd:string"
></part
><part
 name="inParam1"
 type="xsd:string"
></part
><part
 name="inParam2"
 type="xsd:string"
></part
><part
 name="inLocationCode"
 type="xsd:string"
></part
><part
 name="inASCCode"
 type="xsd:string"
></part
><part
 name="inParam3"
 type="xsd:string"
></part
></message
><message
 name="AISDRMChannelInfo_Output"
><part
 name="outASCCode"
 type="xsd:string"
></part
><part
 name="outASCPartnerName"
 type="xsd:string"
></part
><part
 name="outBusinessType"
 type="xsd:string"
></part
><part
 name="outCharacteristic"
 type="xsd:string"
></part
><part
 name="outErrorMessage"
 type="xsd:string"
></part
><part
 name="outFullAddress"
 type="xsd:string"
></part
><part
 name="outLocationCode"
 type="xsd:string"
></part
><part
 name="outMainFax"
 type="xsd:string"
></part
><part
 name="outMainPhone"
 type="xsd:string"
></part
><part
 name="outMobileNo"
 type="xsd:string"
></part
><part
 name="outOperatorClass"
 type="xsd:string"
></part
><part
 name="outParam1"
 type="xsd:string"
></part
><part
 name="outParam10"
 type="xsd:string"
></part
><part
 name="outParam11"
 type="xsd:string"
></part
><part
 name="outParam12"
 type="xsd:string"
></part
><part
 name="outParam13"
 type="xsd:string"
></part
><part
 name="outParam14"
 type="xsd:string"
></part
><part
 name="outParam15"
 type="xsd:string"
></part
><part
 name="outParam16"
 type="xsd:string"
></part
><part
 name="outParam17"
 type="xsd:string"
></part
><part
 name="outParam18"
 type="xsd:string"
></part
><part
 name="outParam19"
 type="xsd:string"
></part
><part
 name="outParam2"
 type="xsd:string"
></part
><part
 name="outParam20"
 type="xsd:string"
></part
><part
 name="outParam21"
 type="xsd:string"
></part
><part
 name="outParam22"
 type="xsd:string"
></part
><part
 name="outParam23"
 type="xsd:string"
></part
><part
 name="outParam24"
 type="xsd:string"
></part
><part
 name="outParam25"
 type="xsd:string"
></part
><part
 name="outParam3"
 type="xsd:string"
></part
><part
 name="outParam4"
 type="xsd:string"
></part
><part
 name="outParam5"
 type="xsd:string"
></part
><part
 name="outParam6"
 type="xsd:string"
></part
><part
 name="outParam7"
 type="xsd:string"
></part
><part
 name="outParam8"
 type="xsd:string"
></part
><part
 name="outParam9"
 type="xsd:string"
></part
><part
 name="outPartnerName"
 type="xsd:string"
></part
><part
 name="outProvince"
 type="xsd:string"
></part
><part
 name="outRegion"
 type="xsd:string"
></part
><part
 name="outStatus"
 type="xsd:string"
></part
><part
 name="outSubRegion"
 type="xsd:string"
></part
><part
 name="outSubType"
 type="xsd:string"
></part
><part
 name="outTitle"
 type="xsd:string"
></part
><part
 name="outType"
 type="xsd:string"
></part
><part
 name="outWTName"
 type="xsd:string"
></part
></message
><portType
 name="AIS_spcDRM_spcChannel_spcInfo"
><operation
 name="AISDRMChannelInfo"
><input
 message="tns:AISDRMChannelInfo_Input"
></input
><output
 message="tns:AISDRMChannelInfo_Output"
></output
></operation
></portType
><binding
 name="AIS_spcDRM_spcChannel_spcInfo"
 type="tns:AIS_spcDRM_spcChannel_spcInfo"
><soap:binding
 transport="http://schemas.xmlsoap.org/soap/http"
 style="rpc"
></soap:binding
><operation
 name="AISDRMChannelInfo"
><soap:operation
 soapAction="rpc/http://siebel.com/asi/:AISDRMChannelInfo"
></soap:operation
><input
><soap:body
 encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
 namespace="http://siebel.com/asi/"
 use="encoded"
></soap:body
></input
><output
><soap:body
 encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
 namespace="http://siebel.com/asi/"
 use="encoded"
></soap:body
></output
></operation
></binding
><service
 name="AIS_spcDRM_spcChannel_spcInfo"
><port
 binding="tns:AIS_spcDRM_spcChannel_spcInfo"
 name="AIS_spcDRM_spcChannel_spcInfo"
><soap:address
 location="http://172.16.252.162/eai/start.swe?SWEExtSource=WebService&amp;SWEExtCmd=Execute&amp;Username=Username&amp;Password=Password"
></soap:address
></port
></service
></definitions
>