<?xml version="1.0" encoding="UTF-8"?><definitions
 xmlns="http://schemas.xmlsoap.org/wsdl/"
 xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
 targetNamespace="http://siebel.com/asi/"
 xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:tns="http://siebel.com/asi/"
><types
></types
><message
 name="CommonCreateActivity_Input"
><part
 name="SRNumber"
 type="xsd:string"
></part
><part
 name="OrderId"
 type="xsd:string"
></part
><part
 name="SerialNumber"
 type="xsd:string"
></part
><part
 name="Done"
 type="xsd:string"
></part
><part
 name="Status"
 type="xsd:string"
></part
><part
 name="Planned"
 type="xsd:string"
></part
><part
 name="CampaignId"
 type="xsd:string"
></part
><part
 name="PrimaryOwnerId"
 type="xsd:string"
></part
><part
 name="Comment"
 type="xsd:string"
></part
><part
 name="NoSoonerThanDate"
 type="xsd:string"
></part
><part
 name="ActivityCategory"
 type="xsd:string"
></part
><part
 name="Reason"
 type="xsd:string"
></part
><part
 name="Type"
 type="xsd:string"
></part
><part
 name="Started"
 type="xsd:string"
></part
><part
 name="DocumentNo"
 type="xsd:string"
></part
><part
 name="MoreInfo"
 type="xsd:string"
></part
><part
 name="CheckOrderId"
 type="xsd:string"
></part
><part
 name="AssetId"
 type="xsd:string"
></part
><part
 name="AccountId"
 type="xsd:string"
></part
><part
 name="SubStatus"
 type="xsd:string"
></part
><part
 name="ContactId"
 type="xsd:string"
></part
><part
 name="ActivitySubCategory"
 type="xsd:string"
></part
><part
 name="Priority"
 type="xsd:string"
></part
><part
 name="PrimaryProductId"
 type="xsd:string"
></part
><part
 name="OwnerName"
 type="xsd:string"
></part
></message
><message
 name="CommonCreateActivity_Output"
><part
 name="ActivityId"
 type="xsd:string"
></part
><part
 name="CheckOrderId"
 type="xsd:string"
></part
><part
 name="Error_spcMessage"
 type="xsd:string"
></part
><part
 name="ErrorMessage"
 type="xsd:string"
></part
></message
><portType
 name="AIS_spcIM_spcCommon_spcCreate_spcActivity"
><operation
 name="CommonCreateActivity"
><input
 message="tns:CommonCreateActivity_Input"
></input
><output
 message="tns:CommonCreateActivity_Output"
></output
></operation
></portType
><binding
 name="AIS_spcIM_spcCommon_spcCreate_spcActivity"
 type="tns:AIS_spcIM_spcCommon_spcCreate_spcActivity"
><soap:binding
 transport="http://schemas.xmlsoap.org/soap/http"
 style="rpc"
></soap:binding
><operation
 name="CommonCreateActivity"
><soap:operation
 soapAction="rpc/http://siebel.com/asi/:CommonCreateActivity"
></soap:operation
><input
><soap:body
 encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
 namespace="http://siebel.com/asi/"
 use="encoded"
></soap:body
></input
><output
><soap:body
 encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
 namespace="http://siebel.com/asi/"
 use="encoded"
></soap:body
></output
></operation
></binding
><service
 name="AIS_spcIM_spcCommon_spcCreate_spcActivity"
><port
 binding="tns:AIS_spcIM_spcCommon_spcCreate_spcActivity"
 name="AIS_spcIM_spcCommon_spcCreate_spcActivity"
><soap:address
 location="http://172.16.252.162/eai/start.swe?SWEExtSource=WebService&amp;SWEExtCmd=Execute&amp;Username=Username&amp;Password=Password"
></soap:address
></port
></service
></definitions
>