<?xml version="1.0" encoding="UTF-8"?><definitions
 xmlns="http://schemas.xmlsoap.org/wsdl/"
 xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
 targetNamespace="http://siebel.com/asi/"
 xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:tns="http://siebel.com/asi/"
><types
></types
><message
 name="CreateTT_Input"
><part
 name="InProblemDate_End"
 type="xsd:string"
></part
><part
 name="InMooban"
 type="xsd:string"
></part
><part
 name="InMobileNumber"
 type="xsd:string"
></part
><part
 name="InIndoor"
 type="xsd:string"
></part
><part
 name="InDestModel"
 type="xsd:string"
></part
><part
 name="InParam1"
 type="xsd:string"
></part
><part
 name="InFloor"
 type="xsd:string"
></part
><part
 name="InAssetId"
 type="xsd:string"
></part
><part
 name="InTumbol"
 type="xsd:string"
></part
><part
 name="InRefArea"
 type="xsd:string"
></part
><part
 name="InCurrentSignalLevel"
 type="xsd:string"
></part
><part
 name="InStreet"
 type="xsd:string"
></part
><part
 name="InParam2"
 type="xsd:string"
></part
><part
 name="InDestMobileNumber"
 type="xsd:string"
></part
><part
 name="InAccountId"
 type="xsd:string"
></part
><part
 name="InUsedCountry"
 type="xsd:string"
></part
><part
 name="InChannel"
 type="xsd:string"
></part
><part
 name="InBuilding"
 type="xsd:string"
></part
><part
 name="InSoi"
 type="xsd:string"
></part
><part
 name="InParam3"
 type="xsd:string"
></part
><part
 name="InModel"
 type="xsd:string"
></part
><part
 name="InSubCategory"
 type="xsd:string"
></part
><part
 name="InProvince"
 type="xsd:string"
></part
><part
 name="InProblemDate"
 type="xsd:string"
></part
><part
 name="InPath"
 type="xsd:string"
></part
><part
 name="InDescription"
 type="xsd:string"
></part
><part
 name="InOption"
 type="xsd:string"
></part
><part
 name="InMaxSignalLevel"
 type="xsd:string"
></part
><part
 name="InHouseNumber"
 type="xsd:string"
></part
><part
 name="InProductName"
 type="xsd:string"
></part
><part
 name="InDestBrand"
 type="xsd:string"
></part
><part
 name="InAmphur"
 type="xsd:string"
></part
><part
 name="InParam5"
 type="xsd:string"
></part
><part
 name="InParam4"
 type="xsd:string"
></part
><part
 name="InContactId"
 type="xsd:string"
></part
><part
 name="InSymptomNote"
 type="xsd:string"
></part
><part
 name="InOtherContactPhone"
 type="xsd:string"
></part
><part
 name="InOperatorName"
 type="xsd:string"
></part
><part
 name="InBrand"
 type="xsd:string"
></part
><part
 name="InContentProvider"
 type="xsd:string"
></part
><part
 name="InCategory"
 type="xsd:string"
></part
></message
><message
 name="CreateTT_Output"
><part
 name="OutErrorMessage"
 type="xsd:string"
></part
><part
 name="OutParam1"
 type="xsd:string"
></part
><part
 name="OutParam2"
 type="xsd:string"
></part
><part
 name="OutParam3"
 type="xsd:string"
></part
><part
 name="OutParam4"
 type="xsd:string"
></part
><part
 name="OutParam5"
 type="xsd:string"
></part
><part
 name="OutResult"
 type="xsd:string"
></part
><part
 name="OutTTNumber"
 type="xsd:string"
></part
></message
><portType
 name="AIS_spcCreate_spcTrouble_spcTicket"
><operation
 name="CreateTT"
><input
 message="tns:CreateTT_Input"
></input
><output
 message="tns:CreateTT_Output"
></output
></operation
></portType
><binding
 name="AIS_spcCreate_spcTrouble_spcTicket"
 type="tns:AIS_spcCreate_spcTrouble_spcTicket"
><soap:binding
 transport="http://schemas.xmlsoap.org/soap/http"
 style="rpc"
></soap:binding
><operation
 name="CreateTT"
><soap:operation
 soapAction="rpc/http://siebel.com/asi/:CreateTT"
></soap:operation
><input
><soap:body
 encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
 namespace="http://siebel.com/asi/"
 use="encoded"
></soap:body
></input
><output
><soap:body
 encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
 namespace="http://siebel.com/asi/"
 use="encoded"
></soap:body
></output
></operation
></binding
><service
 name="AIS_spcCreate_spcTrouble_spcTicket"
><port
 binding="tns:AIS_spcCreate_spcTrouble_spcTicket"
 name="AIS_spcCreate_spcTrouble_spcTicket"
><soap:address
 location="http://172.16.252.162/eai/start.swe?SWEExtSource=WebService&amp;SWEExtCmd=Execute&amp;Username=UserName&amp;Password=Password"
></soap:address
></port
></service
></definitions
>