//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WBBBusinessLayer.IMService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicesBindingSOAP", Namespace="urn:PegaRULES:SOAP:AISNIMIntFBBIntegration:Services")]
    public partial class ServicesService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetFBBOrderNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLeaveMsgReferenceNoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicesService() {
            this.Url = global::WBBBusinessLayer.Properties.Settings.Default.WBBBusinessLayer_IMService_ServicesService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetFBBOrderNoCompletedEventHandler GetFBBOrderNoCompleted;
        
        /// <remarks/>
        public event GetLeaveMsgReferenceNoCompletedEventHandler GetLeaveMsgReferenceNoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:PegaRULES:SOAP:AISNIMIntFBBIntegration:Services#GetFBBOrderNo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetFBBOrderNoResponse", Namespace="urn:PegaRULES:SOAP:AISNIMIntFBBIntegration:Services")]
        public GetFBBOrderNoResponseType GetFBBOrderNo([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:PegaRULES:SOAP:AISNIMIntFBBIntegration:Services")] GetFBBOrderNoRequestType GetFBBOrderNoRequest) {
            object[] results = this.Invoke("GetFBBOrderNo", new object[] {
                        GetFBBOrderNoRequest});
            return ((GetFBBOrderNoResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetFBBOrderNoAsync(GetFBBOrderNoRequestType GetFBBOrderNoRequest) {
            this.GetFBBOrderNoAsync(GetFBBOrderNoRequest, null);
        }
        
        /// <remarks/>
        public void GetFBBOrderNoAsync(GetFBBOrderNoRequestType GetFBBOrderNoRequest, object userState) {
            if ((this.GetFBBOrderNoOperationCompleted == null)) {
                this.GetFBBOrderNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFBBOrderNoOperationCompleted);
            }
            this.InvokeAsync("GetFBBOrderNo", new object[] {
                        GetFBBOrderNoRequest}, this.GetFBBOrderNoOperationCompleted, userState);
        }
        
        private void OnGetFBBOrderNoOperationCompleted(object arg) {
            if ((this.GetFBBOrderNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFBBOrderNoCompleted(this, new GetFBBOrderNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:PegaRULES:SOAP:AISNIMIntFBBIntegration:Services#GetLeaveMsgReferenceNo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetLeaveMsgReferenceNoResponse", Namespace="urn:PegaRULES:SOAP:AISNIMIntFBBIntegration:Services")]
        public GetLeaveMsgReferenceNoResponseType GetLeaveMsgReferenceNo([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:PegaRULES:SOAP:AISNIMIntFBBIntegration:Services")] GetLeaveMsgReferenceNoRequestType GetLeaveMsgReferenceNoRequest) {
            object[] results = this.Invoke("GetLeaveMsgReferenceNo", new object[] {
                        GetLeaveMsgReferenceNoRequest});
            return ((GetLeaveMsgReferenceNoResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetLeaveMsgReferenceNoAsync(GetLeaveMsgReferenceNoRequestType GetLeaveMsgReferenceNoRequest) {
            this.GetLeaveMsgReferenceNoAsync(GetLeaveMsgReferenceNoRequest, null);
        }
        
        /// <remarks/>
        public void GetLeaveMsgReferenceNoAsync(GetLeaveMsgReferenceNoRequestType GetLeaveMsgReferenceNoRequest, object userState) {
            if ((this.GetLeaveMsgReferenceNoOperationCompleted == null)) {
                this.GetLeaveMsgReferenceNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLeaveMsgReferenceNoOperationCompleted);
            }
            this.InvokeAsync("GetLeaveMsgReferenceNo", new object[] {
                        GetLeaveMsgReferenceNoRequest}, this.GetLeaveMsgReferenceNoOperationCompleted, userState);
        }
        
        private void OnGetLeaveMsgReferenceNoOperationCompleted(object arg) {
            if ((this.GetLeaveMsgReferenceNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLeaveMsgReferenceNoCompleted(this, new GetLeaveMsgReferenceNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:PegaRULES:SOAP:AISNIMIntFBBIntegration:Services")]
    public partial class GetFBBOrderNoRequestType {
        
        private string addressAmphurField;
        
        private string addressBuildingField;
        
        private string addressFloorField;
        
        private string addressMooField;
        
        private string addressMoobanField;
        
        private string addressNoField;
        
        private string addressPostCodeField;
        
        private string addressProvinceField;
        
        private string addressRoadField;
        
        private string addressSoiField;
        
        private string addressTumbolField;
        
        private string orderNoField;
        
        private string orderNoStatusField;
        
        private string caseIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressAmphur {
            get {
                return this.addressAmphurField;
            }
            set {
                this.addressAmphurField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressBuilding {
            get {
                return this.addressBuildingField;
            }
            set {
                this.addressBuildingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressFloor {
            get {
                return this.addressFloorField;
            }
            set {
                this.addressFloorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressMoo {
            get {
                return this.addressMooField;
            }
            set {
                this.addressMooField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressMooban {
            get {
                return this.addressMoobanField;
            }
            set {
                this.addressMoobanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressNo {
            get {
                return this.addressNoField;
            }
            set {
                this.addressNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressPostCode {
            get {
                return this.addressPostCodeField;
            }
            set {
                this.addressPostCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressProvince {
            get {
                return this.addressProvinceField;
            }
            set {
                this.addressProvinceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressRoad {
            get {
                return this.addressRoadField;
            }
            set {
                this.addressRoadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressSoi {
            get {
                return this.addressSoiField;
            }
            set {
                this.addressSoiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressTumbol {
            get {
                return this.addressTumbolField;
            }
            set {
                this.addressTumbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderNoStatus {
            get {
                return this.orderNoStatusField;
            }
            set {
                this.orderNoStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CaseID {
            get {
                return this.caseIDField;
            }
            set {
                this.caseIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:PegaRULES:SOAP:AISNIMIntFBBIntegration:Services")]
    public partial class GetLeaveMsgReferenceNoResponseType {
        
        private string returnCodeField;
        
        private string returnMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReturnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:PegaRULES:SOAP:AISNIMIntFBBIntegration:Services")]
    public partial class GetLeaveMsgReferenceNoRequestType {
        
        private string contactMobileNoField;
        
        private string customerLastNameField;
        
        private string customerNameField;
        
        private string referenceNoField;
        
        private string referenceNoStatusField;
        
        private string addressAmphurField;
        
        private string addressBuildingField;
        
        private string addressFloorField;
        
        private string addressMooField;
        
        private string addressMoobanField;
        
        private string addressNoField;
        
        private string addressPostCodeField;
        
        private string addressProvinceField;
        
        private string addressRoadField;
        
        private string addressSoiField;
        
        private string addressTumbolField;
        
        private string inServiceField;
        
        private string caseIDField;
        
        private string productTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContactMobileNo {
            get {
                return this.contactMobileNoField;
            }
            set {
                this.contactMobileNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerLastName {
            get {
                return this.customerLastNameField;
            }
            set {
                this.customerLastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReferenceNo {
            get {
                return this.referenceNoField;
            }
            set {
                this.referenceNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReferenceNoStatus {
            get {
                return this.referenceNoStatusField;
            }
            set {
                this.referenceNoStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressAmphur {
            get {
                return this.addressAmphurField;
            }
            set {
                this.addressAmphurField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressBuilding {
            get {
                return this.addressBuildingField;
            }
            set {
                this.addressBuildingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressFloor {
            get {
                return this.addressFloorField;
            }
            set {
                this.addressFloorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressMoo {
            get {
                return this.addressMooField;
            }
            set {
                this.addressMooField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressMooban {
            get {
                return this.addressMoobanField;
            }
            set {
                this.addressMoobanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressNo {
            get {
                return this.addressNoField;
            }
            set {
                this.addressNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressPostCode {
            get {
                return this.addressPostCodeField;
            }
            set {
                this.addressPostCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressProvince {
            get {
                return this.addressProvinceField;
            }
            set {
                this.addressProvinceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressRoad {
            get {
                return this.addressRoadField;
            }
            set {
                this.addressRoadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressSoi {
            get {
                return this.addressSoiField;
            }
            set {
                this.addressSoiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressTumbol {
            get {
                return this.addressTumbolField;
            }
            set {
                this.addressTumbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InService {
            get {
                return this.inServiceField;
            }
            set {
                this.inServiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CaseID {
            get {
                return this.caseIDField;
            }
            set {
                this.caseIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProductType {
            get {
                return this.productTypeField;
            }
            set {
                this.productTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:PegaRULES:SOAP:AISNIMIntFBBIntegration:Services")]
    public partial class GetFBBOrderNoResponseType {
        
        private string returnCodeField;
        
        private string returnMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReturnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetFBBOrderNoCompletedEventHandler(object sender, GetFBBOrderNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFBBOrderNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFBBOrderNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetFBBOrderNoResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetFBBOrderNoResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetLeaveMsgReferenceNoCompletedEventHandler(object sender, GetLeaveMsgReferenceNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLeaveMsgReferenceNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLeaveMsgReferenceNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetLeaveMsgReferenceNoResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetLeaveMsgReferenceNoResponseType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591