namespace WBBEntity.PanelModels
{
    public class SavePaymentLogModel
    {
        public string ACTION { get; set; }
        public string PAYMENT_ORDER_ID { get; set; }
        public string PROCESS_NAME { get; set; }
        public string ENDPOINT { get; set; }
        public string REQ_PROJECT_CODE { get; set; }
        public string REQ_COMMAND { get; set; }
        public string REQ_SID { get; set; }
        public string REQ_REDIRECT_URL { get; set; }
        public string REQ_MERCHANT_ID { get; set; }
        public string REQ_ORDER_ID { get; set; }
        public string REQ_CURRENCY { get; set; }
        public string REQ_PURCHASE_AMT { get; set; }
        public string REQ_PAYMENT_METHOD { get; set; }
        public string REQ_PRODUCT_DESC { get; set; }
        public string REQ_REF1 { get; set; }
        public string REQ_REF2 { get; set; }
        public string REQ_REF3 { get; set; }
        public string REQ_REF4 { get; set; }
        public string REQ_REF5 { get; set; }
        public string REQ_INTEGRITY_STR { get; set; }
        public string REQ_SMS_FLAG { get; set; }
        public string REQ_SMS_MOBILE { get; set; }
        public string REQ_MOBILE_NO { get; set; }
        public string REQ_TOKEN_KEY { get; set; }
        public string REQ_ORDER_EXPIRE { get; set; }
        public string RESP_STATUS { get; set; }
        public string RESP_RESP_CODE { get; set; }
        public string RESP_RESP_DESC { get; set; }
        public string RESP_SALE_ID { get; set; }
        public string RESP_ENDPOINT_URL { get; set; }
        public string RESP_DETAIL1 { get; set; }
        public string RESP_DETAIL2 { get; set; }
        public string RESP_DETAIL3 { get; set; }
        public string POST_STATUS { get; set; }
        public string POST_RESP_CODE { get; set; }
        public string POST_RESP_DESC { get; set; }
        public string POST_TRAN_ID { get; set; }
        public string POST_SALE_ID { get; set; }
        public string POST_ORDER_ID { get; set; }
        public string POST_CURRENCY { get; set; }
        public string POST_EXCHANGE_RATE { get; set; }
        public string POST_PURCHASE_AMT { get; set; }
        public string POST_AMOUNT { get; set; }
        public string POST_INC_CUSTOMER_FEE { get; set; }
        public string POST_EXC_CUSTOMER_FEE { get; set; }
        public string POST_PAYMENT_STATUS { get; set; }
        public string POST_PAYMENT_CODE { get; set; }
        public string POST_ORDER_EXPIRE_DATE { get; set; }
        //18.10 : QR Code
        public string REQ_APP_ID { get; set; }
        public string REQ_APP_SECRET { get; set; }
        public string REQ_CHANNEL { get; set; }
        public string REQ_QR_TYPE { get; set; }
        public string REQ_TERMINAL_ID { get; set; }
        public string REQ_SERVICE_ID { get; set; }
        public string REQ_LOCATION_NAME { get; set; }
        public string REQ_TRAN_ID { get; set; }
        public string RESP_QR_FORMAT { get; set; }
        public string RESP_QR_CODE_STR { get; set; }
        public string RESP_QR_CODE_VALIDITY { get; set; }
        public string RESP_REFERENCE { get; set; }
        public string RESP_TRAN_DTM { get; set; }
        public string RESP_TRAN_ID { get; set; }
        public string RESP_SERVICE_ID { get; set; }
        public string RESP_TERMINAL_ID { get; set; }
        public string RESP_LOCATION_NAME { get; set; }
        public string RESP_AMOUNT { get; set; }
        public string RESP_SOF { get; set; }
        public string RESP_QR_TYPE { get; set; }
        public string RESP_REFUND_DT { get; set; }
        public string RESP_DISPUTE_ID { get; set; }
        public string RESP_DISPUT_STATUS { get; set; }
        public string RESP_DISPUT_REASON_ID { get; set; }
        public string RESP_REF1 { get; set; }
        public string RESP_REF2 { get; set; }
        public string RESP_REF3 { get; set; }
        public string RESP_REF4 { get; set; }
        public string RESP_REF5 { get; set; }
        public string POST_TRAN_DTM { get; set; }
        public string POST_SERVICE_ID { get; set; }
        public string POST_TERMINAL_ID { get; set; }
        public string POST_LOCATION_NAME { get; set; }
        public string POST_SOF { get; set; }
        public string POST_QR_TYPE { get; set; }
        public string POST_REF1 { get; set; }
        public string POST_REF2 { get; set; }
        public string POST_REF3 { get; set; }
        public string POST_REF4 { get; set; }
        public string POST_REF5 { get; set; }
    }
}
