//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WBBBusinessLayer.WTTxInventory {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WTTxInventoryServiceSoapBinding", Namespace="http://ws.wttx.ais.co.th/")]
    public partial class WTTxInventoryService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback releaseWttxGridInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback reserveWttxGridInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelWttxGridInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryWttxGridInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback renewWttxGridInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback confirmWttxGridInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WTTxInventoryService() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = global::WBBBusinessLayer.Properties.Settings.Default.WBBBusinessLayer_WTTxInventory_WTTxInventoryService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event releaseWttxGridInfoCompletedEventHandler releaseWttxGridInfoCompleted;
        
        /// <remarks/>
        public event reserveWttxGridInfoCompletedEventHandler reserveWttxGridInfoCompleted;
        
        /// <remarks/>
        public event cancelWttxGridInfoCompletedEventHandler cancelWttxGridInfoCompleted;
        
        /// <remarks/>
        public event queryWttxGridInfoCompletedEventHandler queryWttxGridInfoCompleted;
        
        /// <remarks/>
        public event renewWttxGridInfoCompletedEventHandler renewWttxGridInfoCompleted;
        
        /// <remarks/>
        public event confirmWttxGridInfoCompletedEventHandler confirmWttxGridInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ReleaseWttxGridInfo", RequestNamespace="http://ws.wttx.ais.co.th/", ResponseNamespace="http://ws.wttx.ais.co.th/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public responseMsg releaseWttxGridInfo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string customerId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string refId) {
            object[] results = this.Invoke("releaseWttxGridInfo", new object[] {
                        customerId,
                        refId});
            return ((responseMsg)(results[0]));
        }
        
        /// <remarks/>
        public void releaseWttxGridInfoAsync(string customerId, string refId) {
            this.releaseWttxGridInfoAsync(customerId, refId, null);
        }
        
        /// <remarks/>
        public void releaseWttxGridInfoAsync(string customerId, string refId, object userState) {
            if ((this.releaseWttxGridInfoOperationCompleted == null)) {
                this.releaseWttxGridInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreleaseWttxGridInfoOperationCompleted);
            }
            this.InvokeAsync("releaseWttxGridInfo", new object[] {
                        customerId,
                        refId}, this.releaseWttxGridInfoOperationCompleted, userState);
        }
        
        private void OnreleaseWttxGridInfoOperationCompleted(object arg) {
            if ((this.releaseWttxGridInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.releaseWttxGridInfoCompleted(this, new releaseWttxGridInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ReserveWttxGridInfo", RequestNamespace="http://ws.wttx.ais.co.th/", ResponseNamespace="http://ws.wttx.ais.co.th/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public responseMsg reserveWttxGridInfo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string gridId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string reservedExpTime, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string refId) {
            object[] results = this.Invoke("reserveWttxGridInfo", new object[] {
                        gridId,
                        reservedExpTime,
                        refId});
            return ((responseMsg)(results[0]));
        }
        
        /// <remarks/>
        public void reserveWttxGridInfoAsync(string gridId, string reservedExpTime, string refId) {
            this.reserveWttxGridInfoAsync(gridId, reservedExpTime, refId, null);
        }
        
        /// <remarks/>
        public void reserveWttxGridInfoAsync(string gridId, string reservedExpTime, string refId, object userState) {
            if ((this.reserveWttxGridInfoOperationCompleted == null)) {
                this.reserveWttxGridInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreserveWttxGridInfoOperationCompleted);
            }
            this.InvokeAsync("reserveWttxGridInfo", new object[] {
                        gridId,
                        reservedExpTime,
                        refId}, this.reserveWttxGridInfoOperationCompleted, userState);
        }
        
        private void OnreserveWttxGridInfoOperationCompleted(object arg) {
            if ((this.reserveWttxGridInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.reserveWttxGridInfoCompleted(this, new reserveWttxGridInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:CancelWttxGridInfo", RequestNamespace="http://ws.wttx.ais.co.th/", ResponseNamespace="http://ws.wttx.ais.co.th/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public responseMsg cancelWttxGridInfo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string reservedId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string refId) {
            object[] results = this.Invoke("cancelWttxGridInfo", new object[] {
                        reservedId,
                        refId});
            return ((responseMsg)(results[0]));
        }
        
        /// <remarks/>
        public void cancelWttxGridInfoAsync(string reservedId, string refId) {
            this.cancelWttxGridInfoAsync(reservedId, refId, null);
        }
        
        /// <remarks/>
        public void cancelWttxGridInfoAsync(string reservedId, string refId, object userState) {
            if ((this.cancelWttxGridInfoOperationCompleted == null)) {
                this.cancelWttxGridInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelWttxGridInfoOperationCompleted);
            }
            this.InvokeAsync("cancelWttxGridInfo", new object[] {
                        reservedId,
                        refId}, this.cancelWttxGridInfoOperationCompleted, userState);
        }
        
        private void OncancelWttxGridInfoOperationCompleted(object arg) {
            if ((this.cancelWttxGridInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelWttxGridInfoCompleted(this, new cancelWttxGridInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:QueryWttxGridInfo", RequestNamespace="http://ws.wttx.ais.co.th/", ResponseNamespace="http://ws.wttx.ais.co.th/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wttxxGridInfo queryWttxGridInfo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string gridId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string refId) {
            object[] results = this.Invoke("queryWttxGridInfo", new object[] {
                        gridId,
                        refId});
            return ((wttxxGridInfo)(results[0]));
        }
        
        /// <remarks/>
        public void queryWttxGridInfoAsync(string gridId, string refId) {
            this.queryWttxGridInfoAsync(gridId, refId, null);
        }
        
        /// <remarks/>
        public void queryWttxGridInfoAsync(string gridId, string refId, object userState) {
            if ((this.queryWttxGridInfoOperationCompleted == null)) {
                this.queryWttxGridInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryWttxGridInfoOperationCompleted);
            }
            this.InvokeAsync("queryWttxGridInfo", new object[] {
                        gridId,
                        refId}, this.queryWttxGridInfoOperationCompleted, userState);
        }
        
        private void OnqueryWttxGridInfoOperationCompleted(object arg) {
            if ((this.queryWttxGridInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryWttxGridInfoCompleted(this, new queryWttxGridInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:RenewWttxGridInfo", RequestNamespace="http://ws.wttx.ais.co.th/", ResponseNamespace="http://ws.wttx.ais.co.th/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public responseMsg renewWttxGridInfo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string customerId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string refId) {
            object[] results = this.Invoke("renewWttxGridInfo", new object[] {
                        customerId,
                        refId});
            return ((responseMsg)(results[0]));
        }
        
        /// <remarks/>
        public void renewWttxGridInfoAsync(string customerId, string refId) {
            this.renewWttxGridInfoAsync(customerId, refId, null);
        }
        
        /// <remarks/>
        public void renewWttxGridInfoAsync(string customerId, string refId, object userState) {
            if ((this.renewWttxGridInfoOperationCompleted == null)) {
                this.renewWttxGridInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrenewWttxGridInfoOperationCompleted);
            }
            this.InvokeAsync("renewWttxGridInfo", new object[] {
                        customerId,
                        refId}, this.renewWttxGridInfoOperationCompleted, userState);
        }
        
        private void OnrenewWttxGridInfoOperationCompleted(object arg) {
            if ((this.renewWttxGridInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.renewWttxGridInfoCompleted(this, new renewWttxGridInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ConfirmWttxGridInfo", RequestNamespace="http://ws.wttx.ais.co.th/", ResponseNamespace="http://ws.wttx.ais.co.th/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public responseMsg confirmWttxGridInfo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string reservedId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string customerId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string refId) {
            object[] results = this.Invoke("confirmWttxGridInfo", new object[] {
                        reservedId,
                        customerId,
                        refId});
            return ((responseMsg)(results[0]));
        }
        
        /// <remarks/>
        public void confirmWttxGridInfoAsync(string reservedId, string customerId, string refId) {
            this.confirmWttxGridInfoAsync(reservedId, customerId, refId, null);
        }
        
        /// <remarks/>
        public void confirmWttxGridInfoAsync(string reservedId, string customerId, string refId, object userState) {
            if ((this.confirmWttxGridInfoOperationCompleted == null)) {
                this.confirmWttxGridInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconfirmWttxGridInfoOperationCompleted);
            }
            this.InvokeAsync("confirmWttxGridInfo", new object[] {
                        reservedId,
                        customerId,
                        refId}, this.confirmWttxGridInfoOperationCompleted, userState);
        }
        
        private void OnconfirmWttxGridInfoOperationCompleted(object arg) {
            if ((this.confirmWttxGridInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.confirmWttxGridInfoCompleted(this, new confirmWttxGridInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wttx.ais.co.th/")]
    public partial class responseMsg {
        
        private string reservedIdField;
        
        private string responseCodeField;
        
        private string responseMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reservedId {
            get {
                return this.reservedIdField;
            }
            set {
                this.reservedIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string responseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                this.responseMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wttx.ais.co.th/")]
    public partial class wttxxGridInfo {
        
        private string gridIdField;
        
        private string lastUpdateTimeField;
        
        private string latitudeField;
        
        private string longitudeField;
        
        private string maxBandwithField;
        
        private int maxCustomerField;
        
        private int numberOfCustomerField;
        
        private string onServiceField;
        
        private string provinceEngField;
        
        private string provinceThaField;
        
        private string regionField;
        
        private responseMsg respMsgField;
        
        private string scaleXkmField;
        
        private string scaleYkmField;
        
        private string utilizationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gridId {
            get {
                return this.gridIdField;
            }
            set {
                this.gridIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lastUpdateTime {
            get {
                return this.lastUpdateTimeField;
            }
            set {
                this.lastUpdateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string maxBandwith {
            get {
                return this.maxBandwithField;
            }
            set {
                this.maxBandwithField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int maxCustomer {
            get {
                return this.maxCustomerField;
            }
            set {
                this.maxCustomerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int numberOfCustomer {
            get {
                return this.numberOfCustomerField;
            }
            set {
                this.numberOfCustomerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string onService {
            get {
                return this.onServiceField;
            }
            set {
                this.onServiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string provinceEng {
            get {
                return this.provinceEngField;
            }
            set {
                this.provinceEngField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string provinceTha {
            get {
                return this.provinceThaField;
            }
            set {
                this.provinceThaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public responseMsg respMsg {
            get {
                return this.respMsgField;
            }
            set {
                this.respMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string scaleXkm {
            get {
                return this.scaleXkmField;
            }
            set {
                this.scaleXkmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string scaleYkm {
            get {
                return this.scaleYkmField;
            }
            set {
                this.scaleYkmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string utilization {
            get {
                return this.utilizationField;
            }
            set {
                this.utilizationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void releaseWttxGridInfoCompletedEventHandler(object sender, releaseWttxGridInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class releaseWttxGridInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal releaseWttxGridInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public responseMsg Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((responseMsg)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void reserveWttxGridInfoCompletedEventHandler(object sender, reserveWttxGridInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class reserveWttxGridInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal reserveWttxGridInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public responseMsg Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((responseMsg)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void cancelWttxGridInfoCompletedEventHandler(object sender, cancelWttxGridInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelWttxGridInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelWttxGridInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public responseMsg Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((responseMsg)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void queryWttxGridInfoCompletedEventHandler(object sender, queryWttxGridInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryWttxGridInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryWttxGridInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wttxxGridInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wttxxGridInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void renewWttxGridInfoCompletedEventHandler(object sender, renewWttxGridInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class renewWttxGridInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal renewWttxGridInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public responseMsg Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((responseMsg)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void confirmWttxGridInfoCompletedEventHandler(object sender, confirmWttxGridInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class confirmWttxGridInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal confirmWttxGridInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public responseMsg Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((responseMsg)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591