//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WBBBusinessLayer.FBBSAPOnlineRevalue {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_Z_FIAM_FBSS_REVALUATION_ASSETBinding", Namespace="urn:ais.co.th:FI:FBSS:Z_FIAM_FBSS_REVALUATION_ASSET")]
    public partial class SI_Z_FIAM_FBSS_REVALUATION_ASSETService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_Z_FIAM_FBSS_REVALUATION_ASSETOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_Z_FIAM_FBSS_REVALUATION_ASSETService() {
            this.Url = global::WBBBusinessLayer.Properties.Settings.Default.WBBBusinessLayer_FBBSAPOnlineRevalue_SI_Z_FIAM_FBSS_REVALUATION_ASSETService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_Z_FIAM_FBSS_REVALUATION_ASSETCompletedEventHandler SI_Z_FIAM_FBSS_REVALUATION_ASSETCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", RequestElementName="Z_FIAM_FBSS_REVALUATION_ASSET", RequestNamespace="urn:sap-com:document:sap:rfc:functions", ResponseElementName="Z_FIAM_FBSS_REVALUATION_ASSET.Response", ResponseNamespace="urn:sap-com:document:sap:rfc:functions", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("MESSAGE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SI_Z_FIAM_FBSS_REVALUATION_ASSET([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] ref string ACTION, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] ref string INTERNET_NO, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] ref string MAIN_ASSET, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] ref string RUN_GROUP, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] ref string SUBNUMBER, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] ref string TRANS_ID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ASSET_DATE, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string COM_CODE, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string DOC_DATE, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ITEM_TEXT, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string POST_DATE, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string REF_DOC_NO, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string NUMBER_MESSAGE) {
            object[] results = this.Invoke("SI_Z_FIAM_FBSS_REVALUATION_ASSET", new object[] {
                        ACTION,
                        INTERNET_NO,
                        MAIN_ASSET,
                        RUN_GROUP,
                        SUBNUMBER,
                        TRANS_ID,
                        ASSET_DATE,
                        COM_CODE,
                        DOC_DATE,
                        ITEM_TEXT,
                        POST_DATE,
                        REF_DOC_NO});
            ACTION = ((string)(results[1]));
            INTERNET_NO = ((string)(results[2]));
            MAIN_ASSET = ((string)(results[3]));
            RUN_GROUP = ((string)(results[4]));
            SUBNUMBER = ((string)(results[5]));
            TRANS_ID = ((string)(results[6]));
            NUMBER_MESSAGE = ((string)(results[7]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SI_Z_FIAM_FBSS_REVALUATION_ASSETAsync(string ACTION, string INTERNET_NO, string MAIN_ASSET, string RUN_GROUP, string SUBNUMBER, string TRANS_ID, string ASSET_DATE, string COM_CODE, string DOC_DATE, string ITEM_TEXT, string POST_DATE, string REF_DOC_NO) {
            this.SI_Z_FIAM_FBSS_REVALUATION_ASSETAsync(ACTION, INTERNET_NO, MAIN_ASSET, RUN_GROUP, SUBNUMBER, TRANS_ID, ASSET_DATE, COM_CODE, DOC_DATE, ITEM_TEXT, POST_DATE, REF_DOC_NO, null);
        }
        
        /// <remarks/>
        public void SI_Z_FIAM_FBSS_REVALUATION_ASSETAsync(string ACTION, string INTERNET_NO, string MAIN_ASSET, string RUN_GROUP, string SUBNUMBER, string TRANS_ID, string ASSET_DATE, string COM_CODE, string DOC_DATE, string ITEM_TEXT, string POST_DATE, string REF_DOC_NO, object userState) {
            if ((this.SI_Z_FIAM_FBSS_REVALUATION_ASSETOperationCompleted == null)) {
                this.SI_Z_FIAM_FBSS_REVALUATION_ASSETOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_Z_FIAM_FBSS_REVALUATION_ASSETOperationCompleted);
            }
            this.InvokeAsync("SI_Z_FIAM_FBSS_REVALUATION_ASSET", new object[] {
                        ACTION,
                        INTERNET_NO,
                        MAIN_ASSET,
                        RUN_GROUP,
                        SUBNUMBER,
                        TRANS_ID,
                        ASSET_DATE,
                        COM_CODE,
                        DOC_DATE,
                        ITEM_TEXT,
                        POST_DATE,
                        REF_DOC_NO}, this.SI_Z_FIAM_FBSS_REVALUATION_ASSETOperationCompleted, userState);
        }
        
        private void OnSI_Z_FIAM_FBSS_REVALUATION_ASSETOperationCompleted(object arg) {
            if ((this.SI_Z_FIAM_FBSS_REVALUATION_ASSETCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_Z_FIAM_FBSS_REVALUATION_ASSETCompleted(this, new SI_Z_FIAM_FBSS_REVALUATION_ASSETCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SI_Z_FIAM_FBSS_REVALUATION_ASSETCompletedEventHandler(object sender, SI_Z_FIAM_FBSS_REVALUATION_ASSETCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_Z_FIAM_FBSS_REVALUATION_ASSETCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_Z_FIAM_FBSS_REVALUATION_ASSETCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ACTION {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string INTERNET_NO {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string MAIN_ASSET {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string RUN_GROUP {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string SUBNUMBER {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
        
        /// <remarks/>
        public string TRANS_ID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[6]));
            }
        }
        
        /// <remarks/>
        public string NUMBER_MESSAGE {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[7]));
            }
        }
    }
  /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFBSS_REVALUE_ASSET
    {

        // private string  fLAG_TYPEField;
        private string eNTRY_DATEField;
        private string eNTRY_TIMEField;
        private string eNTRY_BYField;
        private string tRANS_IDField;
        private string iNTERNET_NOField;
        private string aCTIONField;
        private string rUN_GROUPField;
        private string mAIN_ASSETField;
        private string sUBNUMBERField;
        private string cOM_CODEField;
        private string dOC_DATEField;
        private string pOST_DATEField;
        private string aSSET_VALUE_DATEField;

        private string rEF_DOC_NOField;
        private string iTEM_TEXTField;


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENTRY_DATE
        {
            get
            {
                return this.eNTRY_DATEField;
            }
            set
            {
                this.eNTRY_DATEField = value;
            }
        }
        // private string eNTRY_TIMEField;
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENTRY_TIME
        {
            get
            {
                return this.eNTRY_TIMEField;
            }
            set
            {
                this.eNTRY_TIMEField = value;
            }
        }
        //  private string eNTRY_BYField;
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENTRY_BY
        {
            get
            {
                return this.eNTRY_BYField;
            }
            set
            {
                this.eNTRY_BYField = value;
            }
        }
        /// <remarks/>private string  tRANS_IDField;
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TRANS_ID
        {
            get
            {
                return this.tRANS_IDField;
            }
            set
            {
                this.tRANS_IDField = value;
            }
        }
        /// <remarks/> private string  iNTERNET_NOField;
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTERNET_NO
        {
            get
            {
                return this.iNTERNET_NOField;
            }
            set
            {
                this.iNTERNET_NOField = value;
            }
        }
        // private string aCTIONField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACTION
        {
            get
            {
                return this.aCTIONField;
            }
            set
            {
                this.aCTIONField = value;
            }
        }
        /// <remarks/>    private string  rUN_GROUPField;
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RUN_GROUP
        {
            get
            {
                return this.rUN_GROUPField;
            }
            set
            {
                this.rUN_GROUPField = value;
            }
        }
        /// <remarks/>mAIN_ASSETField;
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MAIN_ASSET
        {
            get
            {
                return this.mAIN_ASSETField;
            }
            set
            {
                this.mAIN_ASSETField = value;
            }
        }

        /// <remarks/>sUBNUMBERField;
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SUBNUMBER
        {
            get
            {
                return this.sUBNUMBERField;
            }
            set
            {
                this.sUBNUMBERField = value;
            }
        }
        /// <remarks/>   private string  cOM_CODEField;
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COM_CODE
        {
            get
            {
                return this.cOM_CODEField;
            }
            set
            {
                this.cOM_CODEField = value;
            }
        }

        // private string dOC_DATEField;
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DOC_DATE
        {
            get
            {
                return this.dOC_DATEField;
            }
            set
            {
                this.dOC_DATEField = value;
            }
        }
        // private string pOST_DATEField;
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string POST_DATE
        {
            get
            {
                return this.pOST_DATEField;
            }
            set
            {
                this.pOST_DATEField = value;
            }
        }
        // private string aSSET_VALUUE_DATEField;
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ASSET_VALUE_DATE
        {
            get
            {
                return this.aSSET_VALUE_DATEField;
            }
            set
            {
                this.aSSET_VALUE_DATEField = value;
            }
        }
        //private string rEF_DOC_NOField;
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REF_DOC_NO
        {
            get
            {
                return this.rEF_DOC_NOField;
            }
            set
            {
                this.rEF_DOC_NOField = value;
            }
        }
        // private string iTEM_TEXTField;
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ITEM_TEXT
        {
            get
            {
                return this.iTEM_TEXTField;
            }
            set
            {
                this.iTEM_TEXTField = value;
            }
        }


    }


  /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFBSS_FIXEDASSET_ASSET_OUT_REVALUE
    {

        private string tRANS_IDField;

        private string aCTIONField;

        private string rUN_GROUPField;

        private string iNTERNET_NOField;

        private string aSSET_CODEField;

        private string sUBNUMBERField;

        private string nUMBER_MESSAGEField;

        private string mESSAGEField;



        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TRANS_ID
        {
            get
            {
                return this.tRANS_IDField;
            }
            set
            {
                this.tRANS_IDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACTION
        {
            get
            {
                return this.aCTIONField;
            }
            set
            {
                this.aCTIONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RUN_GROUP
        {
            get
            {
                return this.rUN_GROUPField;
            }
            set
            {
                this.rUN_GROUPField = value;
            }
        }


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTERNET_NO
        {
            get
            {
                return this.iNTERNET_NOField;
            }
            set
            {
                this.iNTERNET_NOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ASSET_CODE
        {
            get
            {
                return this.aSSET_CODEField;
            }
            set
            {
                this.aSSET_CODEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SUBNUMBER
        {
            get
            {
                return this.sUBNUMBERField;
            }
            set
            {
                this.sUBNUMBERField = value;
            }
        }
        // private string nUMBER_MESSAGEField;


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NUMBER_MESSAGE
        {
            get
            {
                return this.nUMBER_MESSAGEField;
            }
            set
            {
                this.nUMBER_MESSAGEField = value;
            }
        }
        // private string mESSAGEField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE
        {
            get
            {
                return this.mESSAGEField;
            }
            set
            {
                this.mESSAGEField = value;
            }
        }

    }
}

#pragma warning restore 1591