//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WBBWeb.EmployeeServices {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EmployeeServiceWebServiceV2ServiceSoapBinding", Namespace="http://com/ais/websrv")]
    public partial class EmployeeServiceWebServiceV2Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getUserEmailListOfSubmoduleOnProgramCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getProgCodeRootOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncUserSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback decreaseCounterOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllPermissionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAuthorizeOfSubmoduleOnProgramCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback logOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback getProgCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPermissionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTokenOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EmployeeServiceWebServiceV2Service() {
            this.Url = global::WBBWeb.Properties.Settings.Default.WBBWeb_EmployeeServices_EmployeeServiceWebServiceV2Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getUserEmailListOfSubmoduleOnProgramCodeCompletedEventHandler getUserEmailListOfSubmoduleOnProgramCodeCompleted;
        
        /// <remarks/>
        public event getProgCodeRootCompletedEventHandler getProgCodeRootCompleted;
        
        /// <remarks/>
        public event syncUserSessionCompletedEventHandler syncUserSessionCompleted;
        
        /// <remarks/>
        public event decreaseCounterCompletedEventHandler decreaseCounterCompleted;
        
        /// <remarks/>
        public event getAllPermissionCompletedEventHandler getAllPermissionCompleted;
        
        /// <remarks/>
        public event getAuthorizeOfSubmoduleOnProgramCodeCompletedEventHandler getAuthorizeOfSubmoduleOnProgramCodeCompleted;
        
        /// <remarks/>
        public event logOutCompletedEventHandler logOutCompleted;
        
        /// <remarks/>
        public event getProgCodeCompletedEventHandler getProgCodeCompleted;
        
        /// <remarks/>
        public event getPermissionCompletedEventHandler getPermissionCompleted;
        
        /// <remarks/>
        public event getTokenCompletedEventHandler getTokenCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/ais/websrv", ResponseNamespace="http://com/ais/websrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public SSOResponse getUserEmailListOfSubmoduleOnProgramCode(string moduleAbv, string progCode) {
            object[] results = this.Invoke("getUserEmailListOfSubmoduleOnProgramCode", new object[] {
                        moduleAbv,
                        progCode});
            return ((SSOResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getUserEmailListOfSubmoduleOnProgramCodeAsync(string moduleAbv, string progCode) {
            this.getUserEmailListOfSubmoduleOnProgramCodeAsync(moduleAbv, progCode, null);
        }
        
        /// <remarks/>
        public void getUserEmailListOfSubmoduleOnProgramCodeAsync(string moduleAbv, string progCode, object userState) {
            if ((this.getUserEmailListOfSubmoduleOnProgramCodeOperationCompleted == null)) {
                this.getUserEmailListOfSubmoduleOnProgramCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserEmailListOfSubmoduleOnProgramCodeOperationCompleted);
            }
            this.InvokeAsync("getUserEmailListOfSubmoduleOnProgramCode", new object[] {
                        moduleAbv,
                        progCode}, this.getUserEmailListOfSubmoduleOnProgramCodeOperationCompleted, userState);
        }
        
        private void OngetUserEmailListOfSubmoduleOnProgramCodeOperationCompleted(object arg) {
            if ((this.getUserEmailListOfSubmoduleOnProgramCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserEmailListOfSubmoduleOnProgramCodeCompleted(this, new getUserEmailListOfSubmoduleOnProgramCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/ais/websrv", ResponseNamespace="http://com/ais/websrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public SSOResponse getProgCodeRoot(string TokenId) {
            object[] results = this.Invoke("getProgCodeRoot", new object[] {
                        TokenId});
            return ((SSOResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getProgCodeRootAsync(string TokenId) {
            this.getProgCodeRootAsync(TokenId, null);
        }
        
        /// <remarks/>
        public void getProgCodeRootAsync(string TokenId, object userState) {
            if ((this.getProgCodeRootOperationCompleted == null)) {
                this.getProgCodeRootOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetProgCodeRootOperationCompleted);
            }
            this.InvokeAsync("getProgCodeRoot", new object[] {
                        TokenId}, this.getProgCodeRootOperationCompleted, userState);
        }
        
        private void OngetProgCodeRootOperationCompleted(object arg) {
            if ((this.getProgCodeRootCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getProgCodeRootCompleted(this, new getProgCodeRootCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/ais/websrv", ResponseNamespace="http://com/ais/websrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public SSOResponse syncUserSession(string TokenId) {
            object[] results = this.Invoke("syncUserSession", new object[] {
                        TokenId});
            return ((SSOResponse)(results[0]));
        }
        
        /// <remarks/>
        public void syncUserSessionAsync(string TokenId) {
            this.syncUserSessionAsync(TokenId, null);
        }
        
        /// <remarks/>
        public void syncUserSessionAsync(string TokenId, object userState) {
            if ((this.syncUserSessionOperationCompleted == null)) {
                this.syncUserSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncUserSessionOperationCompleted);
            }
            this.InvokeAsync("syncUserSession", new object[] {
                        TokenId}, this.syncUserSessionOperationCompleted, userState);
        }
        
        private void OnsyncUserSessionOperationCompleted(object arg) {
            if ((this.syncUserSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncUserSessionCompleted(this, new syncUserSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/ais/websrv", ResponseNamespace="http://com/ais/websrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public SSOResponse decreaseCounter(string TokenId) {
            object[] results = this.Invoke("decreaseCounter", new object[] {
                        TokenId});
            return ((SSOResponse)(results[0]));
        }
        
        /// <remarks/>
        public void decreaseCounterAsync(string TokenId) {
            this.decreaseCounterAsync(TokenId, null);
        }
        
        /// <remarks/>
        public void decreaseCounterAsync(string TokenId, object userState) {
            if ((this.decreaseCounterOperationCompleted == null)) {
                this.decreaseCounterOperationCompleted = new System.Threading.SendOrPostCallback(this.OndecreaseCounterOperationCompleted);
            }
            this.InvokeAsync("decreaseCounter", new object[] {
                        TokenId}, this.decreaseCounterOperationCompleted, userState);
        }
        
        private void OndecreaseCounterOperationCompleted(object arg) {
            if ((this.decreaseCounterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.decreaseCounterCompleted(this, new decreaseCounterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/ais/websrv", ResponseNamespace="http://com/ais/websrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public SSOResponse getAllPermission(string TokenId) {
            object[] results = this.Invoke("getAllPermission", new object[] {
                        TokenId});
            return ((SSOResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getAllPermissionAsync(string TokenId) {
            this.getAllPermissionAsync(TokenId, null);
        }
        
        /// <remarks/>
        public void getAllPermissionAsync(string TokenId, object userState) {
            if ((this.getAllPermissionOperationCompleted == null)) {
                this.getAllPermissionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllPermissionOperationCompleted);
            }
            this.InvokeAsync("getAllPermission", new object[] {
                        TokenId}, this.getAllPermissionOperationCompleted, userState);
        }
        
        private void OngetAllPermissionOperationCompleted(object arg) {
            if ((this.getAllPermissionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllPermissionCompleted(this, new getAllPermissionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/ais/websrv", ResponseNamespace="http://com/ais/websrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public SSOResponse getAuthorizeOfSubmoduleOnProgramCode(string moduleAbv, string progCode) {
            object[] results = this.Invoke("getAuthorizeOfSubmoduleOnProgramCode", new object[] {
                        moduleAbv,
                        progCode});
            return ((SSOResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getAuthorizeOfSubmoduleOnProgramCodeAsync(string moduleAbv, string progCode) {
            this.getAuthorizeOfSubmoduleOnProgramCodeAsync(moduleAbv, progCode, null);
        }
        
        /// <remarks/>
        public void getAuthorizeOfSubmoduleOnProgramCodeAsync(string moduleAbv, string progCode, object userState) {
            if ((this.getAuthorizeOfSubmoduleOnProgramCodeOperationCompleted == null)) {
                this.getAuthorizeOfSubmoduleOnProgramCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAuthorizeOfSubmoduleOnProgramCodeOperationCompleted);
            }
            this.InvokeAsync("getAuthorizeOfSubmoduleOnProgramCode", new object[] {
                        moduleAbv,
                        progCode}, this.getAuthorizeOfSubmoduleOnProgramCodeOperationCompleted, userState);
        }
        
        private void OngetAuthorizeOfSubmoduleOnProgramCodeOperationCompleted(object arg) {
            if ((this.getAuthorizeOfSubmoduleOnProgramCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAuthorizeOfSubmoduleOnProgramCodeCompleted(this, new getAuthorizeOfSubmoduleOnProgramCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/ais/websrv", ResponseNamespace="http://com/ais/websrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public SSOResponse logOut(string TokenId) {
            object[] results = this.Invoke("logOut", new object[] {
                        TokenId});
            return ((SSOResponse)(results[0]));
        }
        
        /// <remarks/>
        public void logOutAsync(string TokenId) {
            this.logOutAsync(TokenId, null);
        }
        
        /// <remarks/>
        public void logOutAsync(string TokenId, object userState) {
            if ((this.logOutOperationCompleted == null)) {
                this.logOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlogOutOperationCompleted);
            }
            this.InvokeAsync("logOut", new object[] {
                        TokenId}, this.logOutOperationCompleted, userState);
        }
        
        private void OnlogOutOperationCompleted(object arg) {
            if ((this.logOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.logOutCompleted(this, new logOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/ais/websrv", ResponseNamespace="http://com/ais/websrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public SSOResponse getProgCode(string TokenId) {
            object[] results = this.Invoke("getProgCode", new object[] {
                        TokenId});
            return ((SSOResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getProgCodeAsync(string TokenId) {
            this.getProgCodeAsync(TokenId, null);
        }
        
        /// <remarks/>
        public void getProgCodeAsync(string TokenId, object userState) {
            if ((this.getProgCodeOperationCompleted == null)) {
                this.getProgCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetProgCodeOperationCompleted);
            }
            this.InvokeAsync("getProgCode", new object[] {
                        TokenId}, this.getProgCodeOperationCompleted, userState);
        }
        
        private void OngetProgCodeOperationCompleted(object arg) {
            if ((this.getProgCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getProgCodeCompleted(this, new getProgCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/ais/websrv", ResponseNamespace="http://com/ais/websrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public SSOResponse getPermission(string TokenId, string progCode) {
            object[] results = this.Invoke("getPermission", new object[] {
                        TokenId,
                        progCode});
            return ((SSOResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getPermissionAsync(string TokenId, string progCode) {
            this.getPermissionAsync(TokenId, progCode, null);
        }
        
        /// <remarks/>
        public void getPermissionAsync(string TokenId, string progCode, object userState) {
            if ((this.getPermissionOperationCompleted == null)) {
                this.getPermissionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPermissionOperationCompleted);
            }
            this.InvokeAsync("getPermission", new object[] {
                        TokenId,
                        progCode}, this.getPermissionOperationCompleted, userState);
        }
        
        private void OngetPermissionOperationCompleted(object arg) {
            if ((this.getPermissionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPermissionCompleted(this, new getPermissionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/ais/websrv", ResponseNamespace="http://com/ais/websrv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public SSOResponse getToken(string username, string password, string module, string ou_type, string projectCode) {
            object[] results = this.Invoke("getToken", new object[] {
                        username,
                        password,
                        module,
                        ou_type,
                        projectCode});
            return ((SSOResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getTokenAsync(string username, string password, string module, string ou_type, string projectCode) {
            this.getTokenAsync(username, password, module, ou_type, projectCode, null);
        }
        
        /// <remarks/>
        public void getTokenAsync(string username, string password, string module, string ou_type, string projectCode, object userState) {
            if ((this.getTokenOperationCompleted == null)) {
                this.getTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTokenOperationCompleted);
            }
            this.InvokeAsync("getToken", new object[] {
                        username,
                        password,
                        module,
                        ou_type,
                        projectCode}, this.getTokenOperationCompleted, userState);
        }
        
        private void OngetTokenOperationCompleted(object arg) {
            if ((this.getTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTokenCompleted(this, new getTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.ais.bean.Permission")]
    public partial class SSOResponse {
        
        private string tokenIdField;
        
        private Message messageField;
        
        private SSOProgCode sSOProgCodeField;
        
        private SSOProgDesc[] sSOProgCodeListField;
        
        private SSOCompCode[] sSOCompCodeField;
        
        private SSOEMailListDetail[] sSOEMailListDetailField;
        
        private SSOAuthorizeSubmodule[] sSOAuthorizeSubmoduleField;
        
        private SSOProgCode[] sSOProgCodecArrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TokenId {
            get {
                return this.tokenIdField;
            }
            set {
                this.tokenIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Message Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SSOProgCode SSOProgCode {
            get {
                return this.sSOProgCodeField;
            }
            set {
                this.sSOProgCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SSOProgCodeList", IsNullable=true)]
        public SSOProgDesc[] SSOProgCodeList {
            get {
                return this.sSOProgCodeListField;
            }
            set {
                this.sSOProgCodeListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SSOCompCode", IsNullable=true)]
        public SSOCompCode[] SSOCompCode {
            get {
                return this.sSOCompCodeField;
            }
            set {
                this.sSOCompCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SSOEMailListDetail", IsNullable=true)]
        public SSOEMailListDetail[] SSOEMailListDetail {
            get {
                return this.sSOEMailListDetailField;
            }
            set {
                this.sSOEMailListDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SSOAuthorizeSubmodule", IsNullable=true)]
        public SSOAuthorizeSubmodule[] SSOAuthorizeSubmodule {
            get {
                return this.sSOAuthorizeSubmoduleField;
            }
            set {
                this.sSOAuthorizeSubmoduleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SSOProgCodecArr", IsNullable=true)]
        public SSOProgCode[] SSOProgCodecArr {
            get {
                return this.sSOProgCodecArrField;
            }
            set {
                this.sSOProgCodecArrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.ais.bean.common")]
    public partial class Message {
        
        private string errorCodeField;
        
        private string tokenIdField;
        
        private string errorMesgField;
        
        private bool flagField;
        
        private string serviceNameField;
        
        private int typeField;
        
        private string serviceTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TokenId {
            get {
                return this.tokenIdField;
            }
            set {
                this.tokenIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorMesg {
            get {
                return this.errorMesgField;
            }
            set {
                this.errorMesgField = value;
            }
        }
        
        /// <remarks/>
        public bool Flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
            }
        }
        
        /// <remarks/>
        public int Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServiceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.ais.bean.Permission")]
    public partial class SSOAuthorizeSubmodule {
        
        private SSOProgCode sSOProgCodeField;
        
        private SSOSubmodule sSOSubmoduleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SSOProgCode SSOProgCode {
            get {
                return this.sSOProgCodeField;
            }
            set {
                this.sSOProgCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SSOSubmodule SSOSubmodule {
            get {
                return this.sSOSubmoduleField;
            }
            set {
                this.sSOSubmoduleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.ais.bean.Permission")]
    public partial class SSOProgCode {
        
        private long userGidField;
        
        private long subMidField;
        
        private long progCodeIdField;
        
        private string progDescField;
        
        private string addField;
        
        private string editField;
        
        private string delField;
        
        private string inqField;
        
        private string procField;
        
        private string oth1Field;
        
        private string oth2Field;
        
        private string oth3Field;
        
        private string oth1_descField;
        
        private string oth2_descField;
        
        private string oth3_descField;
        
        private string progCodeNameField;
        
        /// <remarks/>
        public long UserGid {
            get {
                return this.userGidField;
            }
            set {
                this.userGidField = value;
            }
        }
        
        /// <remarks/>
        public long SubMid {
            get {
                return this.subMidField;
            }
            set {
                this.subMidField = value;
            }
        }
        
        /// <remarks/>
        public long ProgCodeId {
            get {
                return this.progCodeIdField;
            }
            set {
                this.progCodeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProgDesc {
            get {
                return this.progDescField;
            }
            set {
                this.progDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Add {
            get {
                return this.addField;
            }
            set {
                this.addField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Edit {
            get {
                return this.editField;
            }
            set {
                this.editField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Del {
            get {
                return this.delField;
            }
            set {
                this.delField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Inq {
            get {
                return this.inqField;
            }
            set {
                this.inqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Proc {
            get {
                return this.procField;
            }
            set {
                this.procField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Oth1 {
            get {
                return this.oth1Field;
            }
            set {
                this.oth1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Oth2 {
            get {
                return this.oth2Field;
            }
            set {
                this.oth2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Oth3 {
            get {
                return this.oth3Field;
            }
            set {
                this.oth3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Oth1_desc {
            get {
                return this.oth1_descField;
            }
            set {
                this.oth1_descField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Oth2_desc {
            get {
                return this.oth2_descField;
            }
            set {
                this.oth2_descField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Oth3_desc {
            get {
                return this.oth3_descField;
            }
            set {
                this.oth3_descField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProgCodeName {
            get {
                return this.progCodeNameField;
            }
            set {
                this.progCodeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.ais.bean.Permission")]
    public partial class SSOSubmodule {
        
        private string subModuleNameField;
        
        private string subModuleDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SubModuleName {
            get {
                return this.subModuleNameField;
            }
            set {
                this.subModuleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SubModuleDesc {
            get {
                return this.subModuleDescField;
            }
            set {
                this.subModuleDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.ais.bean.Permission")]
    public partial class SSOEMailListDetail {
        
        private SSOProgCode sSOProgCodeField;
        
        private SSOSubmodule sSOSubmoduleField;
        
        private string[] emailListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SSOProgCode SSOProgCode {
            get {
                return this.sSOProgCodeField;
            }
            set {
                this.sSOProgCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SSOSubmodule SSOSubmodule {
            get {
                return this.sSOSubmoduleField;
            }
            set {
                this.sSOSubmoduleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EmailList", IsNullable=true)]
        public string[] EmailList {
            get {
                return this.emailListField;
            }
            set {
                this.emailListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.ais.bean.Permission")]
    public partial class SSOCompCode {
        
        private long userGidField;
        
        private long subMidField;
        
        private long progCodeIdField;
        
        private string compCodeField;
        
        private string compDescField;
        
        private string visibleField;
        
        private string enableField;
        
        private string editField;
        
        private string oth1Field;
        
        private string oth2Field;
        
        private string oth3Field;
        
        private string oth1_descField;
        
        private string oth2_descField;
        
        private string oth3_descField;
        
        private string progCodeNameField;
        
        /// <remarks/>
        public long UserGid {
            get {
                return this.userGidField;
            }
            set {
                this.userGidField = value;
            }
        }
        
        /// <remarks/>
        public long SubMid {
            get {
                return this.subMidField;
            }
            set {
                this.subMidField = value;
            }
        }
        
        /// <remarks/>
        public long ProgCodeId {
            get {
                return this.progCodeIdField;
            }
            set {
                this.progCodeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CompCode {
            get {
                return this.compCodeField;
            }
            set {
                this.compCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CompDesc {
            get {
                return this.compDescField;
            }
            set {
                this.compDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Enable {
            get {
                return this.enableField;
            }
            set {
                this.enableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Edit {
            get {
                return this.editField;
            }
            set {
                this.editField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Oth1 {
            get {
                return this.oth1Field;
            }
            set {
                this.oth1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Oth2 {
            get {
                return this.oth2Field;
            }
            set {
                this.oth2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Oth3 {
            get {
                return this.oth3Field;
            }
            set {
                this.oth3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Oth1_desc {
            get {
                return this.oth1_descField;
            }
            set {
                this.oth1_descField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Oth2_desc {
            get {
                return this.oth2_descField;
            }
            set {
                this.oth2_descField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Oth3_desc {
            get {
                return this.oth3_descField;
            }
            set {
                this.oth3_descField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProgCodeName {
            get {
                return this.progCodeNameField;
            }
            set {
                this.progCodeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.ais.bean.Permission")]
    public partial class SSOProgDesc {
        
        private string progCodeField;
        
        private string progDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProgCode {
            get {
                return this.progCodeField;
            }
            set {
                this.progCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProgDesc {
            get {
                return this.progDescField;
            }
            set {
                this.progDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getUserEmailListOfSubmoduleOnProgramCodeCompletedEventHandler(object sender, getUserEmailListOfSubmoduleOnProgramCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUserEmailListOfSubmoduleOnProgramCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUserEmailListOfSubmoduleOnProgramCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSOResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSOResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getProgCodeRootCompletedEventHandler(object sender, getProgCodeRootCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getProgCodeRootCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getProgCodeRootCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSOResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSOResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void syncUserSessionCompletedEventHandler(object sender, syncUserSessionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncUserSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncUserSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSOResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSOResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void decreaseCounterCompletedEventHandler(object sender, decreaseCounterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class decreaseCounterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal decreaseCounterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSOResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSOResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getAllPermissionCompletedEventHandler(object sender, getAllPermissionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllPermissionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllPermissionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSOResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSOResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getAuthorizeOfSubmoduleOnProgramCodeCompletedEventHandler(object sender, getAuthorizeOfSubmoduleOnProgramCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAuthorizeOfSubmoduleOnProgramCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAuthorizeOfSubmoduleOnProgramCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSOResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSOResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void logOutCompletedEventHandler(object sender, logOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class logOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal logOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSOResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSOResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getProgCodeCompletedEventHandler(object sender, getProgCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getProgCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getProgCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSOResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSOResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getPermissionCompletedEventHandler(object sender, getPermissionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPermissionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPermissionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSOResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSOResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getTokenCompletedEventHandler(object sender, getTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSOResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSOResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591